import { getFieldingRating } from './defense'
import type { BaseRunnerState, BasesState, DefensivePosition, GameCardSnapshot, GameSide, GameState, PendingDecision } from './types'
import { declineSimpleCoreDecision, finishPlateAppearance, finishWithoutPlateAppearance } from './coreGame'
import { catcherStealCheckIsOut, extraBaseEffectiveBaserunning, extraBaseRtsPasses, fieldingCheckIsOut, tagUpEffectiveBaserunning, tagUpOutfieldBonus, tagUpRtsPasses } from './ruleAssertions'

export type DecisionOption={id:string;label:string;detail:string}
export type RunnerAttempt={runner:BaseRunnerState;from:'1B'|'2B'|'3B';to:'2B'|'3B'|'HOME';requiresAttemptId?:string}
export type DecisionView={title:string;description:string;actingSide:GameSide;mode:'single'|'multi_runner'|'roll'|'information';options:DecisionOption[];confirmationLabel:string;confirmationSummary:(ids:string[])=>string}
type OF='LF'|'CF'|'RF'
type BaseName='first'|'second'|'third'
type INFCombo='1B+2B+SS'|'1B+2B+3B'|'1B+3B+SS'
const INF_COMBOS:INFCombo[]=['1B+2B+SS','1B+2B+3B','1B+3B+SS']
function infUsage(state:GameState,side:GameSide):Partial<Record<INFCombo,number>>{return state.infieldDoublePlayUsage?.[side]??{'1B+2B+SS':0,'1B+2B+3B':0,'1B+3B+SS':0}}
function eligibleInfCombos(state:GameState,side:GameSide):INFCombo[]{const u=infUsage(state,side);const min=Math.min(...INF_COMBOS.map(c=>u[c]??0));return INF_COMBOS.filter(c=>(u[c]??0)===min)}
function withInfUse(state:GameState,side:GameSide,combo:INFCombo):GameState{const u=infUsage(state,side);return {...state,infieldDoublePlayUsage:{away:{...(state.infieldDoublePlayUsage?.away??{})},home:{...(state.infieldDoublePlayUsage?.home??{})},[side]:{...u,[combo]:(u[combo]??0)+1}}}}
function comboPositions(combo:INFCombo):DefensivePosition[]{return combo.split('+') as DefensivePosition[]}
function comboDefense(state:GameState,side:GameSide,combo:INFCombo){return comboPositions(combo).reduce((n,p)=>n+fielding(state,side,p),0)}

const other=(s:GameSide):GameSide=>s==='home'?'away':'home'
const offenseSide=(state:GameState):GameSide=>state.half==='top'?'away':'home'
const defenseSide=(state:GameState):GameSide=>other(offenseSide(state))
function replaceDecision(state:GameState,pending:PendingDecision):GameState{return {...state,status:'awaiting_decision',waitingFor:'CONDITIONAL_DECISION',nextActor:pending.actingSide,pendingDecision:pending}}
function nextDecision(state:GameState,args:{type:string;actingSide:GameSide;legalActions:string[];context:Record<string,unknown>}):GameState{return replaceDecision(state,{id:crypto.randomUUID(),ruleCondition:'RC5_CONDITIONAL_GAME_STATE',decisionType:args.type,actingSide:args.actingSide,legalActions:args.legalActions,context:args.context,createdAt:new Date().toISOString()})}
function attemptId(a:RunnerAttempt){return `${a.runner.cardKey}::${a.from}->${a.to}`}
function formatAttempt(a:RunnerAttempt){return `${a.runner.playerName}: ${a.from} → ${a.to==='HOME'?'Home':a.to}`}
function assertPending(state:GameState){if(!state.pendingDecision)throw new Error('No manager decision is pending.');return state.pendingDecision}
function cardFor(state:GameState,side:GameSide,key:string|null|undefined){return key?state.pregame[side].roster?.cards[key]??null:null}
function defenseCard(state:GameState,side:GameSide,pos:DefensivePosition){return cardFor(state,side,state.pregame[side].defensiveAlignment[pos])}
function fielding(state:GameState,side:GameSide,pos:DefensivePosition){const card=defenseCard(state,side,pos);return card?(getFieldingRating(card,pos)??0):0}
function usage(state:GameState,side:GameSide):Record<OF,number>{return state.outfieldThrowUsage?.[side]??{LF:0,CF:0,RF:0}}
function eligibleOF(state:GameState,side:GameSide):OF[]{const u=usage(state,side);const present=(['LF','CF','RF'] as OF[]).filter(p=>defenseCard(state,side,p));if(!present.length)return[];const min=Math.min(...present.map(p=>u[p]));return present.filter(p=>u[p]===min)}
function withOFUse(state:GameState,side:GameSide,pos:OF):GameState{const current=usage(state,side);return {...state,outfieldThrowUsage:{away:{...(state.outfieldThrowUsage?.away??{LF:0,CF:0,RF:0})},home:{...(state.outfieldThrowUsage?.home??{LF:0,CF:0,RF:0})},[side]:{...current,[pos]:current[pos]+1}}}}
function ofOptionId(pos:OF){return `OF::${pos}`}
function baseEntries(state:GameState):Array<[BaseName,BaseRunnerState]> {return ([['first',state.bases.first],['second',state.bases.second],['third',state.bases.third]] as Array<[BaseName,BaseRunnerState|null]>).filter((x):x is [BaseName,BaseRunnerState]=>Boolean(x[1]))}
function starterUsed(state:GameState,side:GameSide){return [...new Set([...state.pregame[side].battingOrderCardKeys,...Object.values(state.pregame[side].defensiveAlignment).filter(Boolean) as string[]])]}
function usedKeys(state:GameState,side:GameSide){return state.appearedCardKeys?.[side]??starterUsed(state,side)}
function benchCards(state:GameState,side:GameSide):GameCardSnapshot[]{const roster=state.pregame[side].roster; if(!roster)return[];const used=new Set(usedKeys(state,side));return Object.values(roster.cards).filter(c=>!used.has(c.cardKey))}
function markAppeared(state:GameState,side:GameSide,key:string){const current=usedKeys(state,side);return {...state,appearedCardKeys:{away:[...(state.appearedCardKeys?.away??starterUsed(state,'away'))],home:[...(state.appearedCardKeys?.home??starterUsed(state,'home'))],[side]:[...new Set([...current,key])]}}}

function extraAttempts(state:GameState):RunnerAttempt[]{const d=state.pendingDecision;const result=String(d?.context.result??'');const pre=d?.context.preBases as BasesState|undefined;if(!pre||(result!=='1B'&&result!=='2B'))return[];if(result==='1B'){const out:RunnerAttempt[]=[];let lead:string|undefined;if(pre.second){const a:RunnerAttempt={runner:pre.second,from:'2B',to:'HOME'};lead=attemptId(a);out.push(a)}if(pre.first)out.push({runner:pre.first,from:'1B',to:'3B',requiresAttemptId:lead});return out}return pre.first?[{runner:pre.first,from:'1B',to:'HOME'}]:[]}
function tagAttempts(state:GameState):RunnerAttempt[]{const pre=state.pendingDecision?.context.preBases as BasesState|undefined;if(!pre)return[];const out:RunnerAttempt[]=[];let a3:string|undefined,a2:string|undefined;if(pre.third){const a:RunnerAttempt={runner:pre.third,from:'3B',to:'HOME'};a3=attemptId(a);out.push(a)}if(pre.second){const a:RunnerAttempt={runner:pre.second,from:'2B',to:'3B',requiresAttemptId:a3};a2=attemptId(a);out.push(a)}if(pre.first)out.push({runner:pre.first,from:'1B',to:'2B',requiresAttemptId:a2});return out}
function naturalStealAttempts(state:GameState):RunnerAttempt[]{const out:RunnerAttempt[]=[];let lead:string|undefined;if(state.bases.third){const a:RunnerAttempt={runner:state.bases.third,from:'3B',to:'HOME'};lead=attemptId(a);out.push(a)}if(state.bases.second){const a:RunnerAttempt={runner:state.bases.second,from:'2B',to:'3B',requiresAttemptId:lead};lead=attemptId(a);out.push(a)}if(state.bases.first)out.push({runner:state.bases.first,from:'1B',to:'2B',requiresAttemptId:lead});return out}
function attemptsFor(state:GameState):RunnerAttempt[]{return (state.pendingDecision?.context.eligibleAttempts as RunnerAttempt[]|undefined)??[]}

function resumeSamePlateAppearance(state:GameState):GameState {return {...state,status:'in_progress',waitingFor:'PITCH_ROLL',nextActor:defenseSide(state),pendingDecision:null,plateAppearance:{...state.plateAppearance,pitchRoll:null,pitchTotal:null,advantage:null,swingRoll:null,chartResult:null}}}
function resumeSwingOnPitcherChart(state:GameState):GameState {return {...state,status:'in_progress',waitingFor:'SWING_ROLL',nextActor:offenseSide(state),pendingDecision:null,plateAppearance:{...state.plateAppearance,pitchRoll:null,pitchTotal:null,advantage:'pitcher',swingRoll:null,chartResult:null}}}
function runnerFromCard(card:GameCardSnapshot,useDefault=false):BaseRunnerState{return{cardKey:card.cardKey,playerName:card.playerName,baserunning:useDefault?10:(card.hitter.baserunning??10),stolenBase:useDefault?10:(card.hitter.stolenBase??10)}}
function removeRunner(bases:BasesState,key:string){if(bases.first?.cardKey===key)bases.first=null;if(bases.second?.cardKey===key)bases.second=null;if(bases.third?.cardKey===key)bases.third=null}
function placeRunner(bases:BasesState,base:BaseName,runner:BaseRunnerState){removeRunner(bases,runner.cardKey);bases[base]=runner}
function score(state:GameState,side:GameSide,n=1):GameState{return {...state,score:{...state.score,[side]:state.score[side]+n}}}
function awardWalk(state:GameState):GameState {const side=offenseSide(state);const key=state.plateAppearance.batterCardKey;const card=cardFor(state,side,key);if(!card)throw new Error('Current batter is unavailable.');const r=runnerFromCard(card,state.pregame[side].defaultBatterCardKeys.includes(card.cardKey) || card.hitter.onBase === null);let next={...state,bases:{...state.bases}};removeRunner(next.bases,r.cardKey);if(next.bases.first){if(next.bases.second){if(next.bases.third)next=score(next,side);next.bases.third=next.bases.second}next.bases.second=next.bases.first}placeRunner(next.bases,'first',r);return finishPlateAppearance({...next,status:'in_progress',pendingDecision:null})}
function advanceForcedOne(state:GameState,hitterSafe:boolean,hitterOut:boolean,holdThird=false):GameState {const side=offenseSide(state);const key=state.plateAppearance.batterCardKey;const card=cardFor(state,side,key);if(!card)throw new Error('Batter unavailable.');const b=structuredClone(state.bases);removeRunner(b,card.cardKey);let next={...state,bases:b};if(b.first){if(b.second){if(b.third && !holdThird)next=score(next,side);if(!holdThird)b.third=b.second}else if(!holdThird&&b.third){/* third not forced */}b.second=b.first;b.first=null}if(hitterSafe)placeRunner(b,'first',runnerFromCard(card,state.pregame[side].defaultBatterCardKeys.includes(card.cardKey) || card.hitter.onBase === null));if(hitterOut)next.outs=Math.min(3,next.outs+1) as 0|1|2|3;return finishPlateAppearance({...next,status:'in_progress',pendingDecision:null})}
function leadRunner(state:GameState){return state.bases.third??state.bases.second??state.bases.first}

function applyEntryMode(state:GameState,side:GameSide,key:string,useDefault:boolean){let next=markAppeared(state,side,key);const pre={...next.pregame[side],defaultBatterCardKeys:[...next.pregame[side].defaultBatterCardKeys],defaultPitcherCardKeys:[...(next.pregame[side].defaultPitcherCardKeys??[])]};if(useDefault){pre.defaultBatterCardKeys=[...new Set([...pre.defaultBatterCardKeys,key])];pre.defaultPitcherCardKeys=[...new Set([...(pre.defaultPitcherCardKeys??[]),key])]}next={...next,pregame:{...next.pregame,[side]:pre}};return next}
function replaceOneLineupSlot(order:string[],outgoing:string,replacement:string):string[]{const next=[...order];if(next.includes(replacement))throw new Error('Replacement player is already active in the batting order.');const slots=next.flatMap((key,index)=>key===outgoing?[index]:[]);if(slots.length>1)throw new Error(`Invalid batting order: ${outgoing} occupies multiple lineup slots.`);if(slots.length===1)next[slots[0]]=replacement;return next}
function assertUniqueLineup(order:string[]){if(new Set(order).size!==order.length)throw new Error('Invalid batting order: duplicate active player detected after substitution.')}
function replacePlayerEverywhere(state:GameState,side:GameSide,outgoing:string,replacement:string,base?:BaseName):GameState {let next={...state,pregame:{...state.pregame,[side]:{...state.pregame[side],battingOrderCardKeys:[...state.pregame[side].battingOrderCardKeys],defensiveAlignment:{...state.pregame[side].defensiveAlignment}}},bases:{...state.bases},plateAppearance:{...state.plateAppearance}};const pre=next.pregame[side];pre.battingOrderCardKeys=replaceOneLineupSlot(pre.battingOrderCardKeys,outgoing,replacement);for(const pos of Object.keys(pre.defensiveAlignment) as DefensivePosition[])if(pre.defensiveAlignment[pos]===outgoing)pre.defensiveAlignment[pos]=replacement;if(base){const card=cardFor(next,side,replacement);if(!card)throw new Error('Replacement card unavailable.');placeRunner(next.bases,base,runnerFromCard(card,pre.defaultBatterCardKeys.includes(replacement) || card.hitter.onBase === null))}if(side===offenseSide(next)&&next.plateAppearance.batterCardKey===outgoing)next.plateAppearance.batterCardKey=replacement;if(side===defenseSide(next)&&next.plateAppearance.pitcherCardKey===outgoing)next.plateAppearance.pitcherCardKey=replacement;assertUniqueLineup(pre.battingOrderCardKeys);return next}

export function getPrePitchActions(state:GameState):DecisionOption[]{if(state.status!=='in_progress'||state.waitingFor!=='PITCH_ROLL'||state.pendingDecision)return[];const off=offenseSide(state),def=defenseSide(state);const out:DecisionOption[]=[];const catcherDef=fielding(state,def,'C');if(baseEntries(state).length && (!(state.naturalStolenBaseUsed?.[off]??false)||catcherDef<0))out.push({id:'NATURAL_STEAL',label:'Natural Steal',detail:catcherDef<0?'Unlimited while catcher DEF is negative':'Uses this team’s one natural steal attempt'});out.push({id:'INTENTIONAL_WALK',label:'Intentional Walk',detail:'Defense awards the current hitter first base'});const b=state.bases;if((b.first&&!b.second)||(b.second&&!b.third)||(b.first&&b.second&&!b.third)||(b.first&&b.third&&!b.second))out.push({id:'SAC_BUNT',label:'Sacrifice Bunt',detail:'Offense declares bunt before any pitch roll'});if(b.third && !(b.first&&b.second) && !state.plateAppearance.infieldIn)out.push({id:'SQUEEZE_BUNT',label:'Squeeze Bunt',detail:'Runner on 3B; bases not loaded; infield-in not declared'});if(b.third&&state.outs<2&&!state.plateAppearance.infieldIn)out.push({id:'INFIELD_IN',label:'Infield In',detail:'Defense locks infield-in for this plate appearance'});if(benchCards(state,off).length){out.push({id:'PINCH_HITTER',label:'Pinch Hitter',detail:'Replace the current hitter with an unused bench player'});if(baseEntries(state).length)out.push({id:'PINCH_RUNNER',label:'Pinch Runner',detail:'Replace an existing runner with an unused bench player'})}if(benchCards(state,def).length){out.push({id:'DEFENSIVE_SUB',label:'Defensive Substitution',detail:'Replace a fielder and inherit that defensive position'});out.push({id:'PITCHING_CHANGE',label:'Pitching Change',detail:'Replace the current pitcher from the bench'});if(!state.pregame[def].roster?.useDh && benchCards(state,def).length>=2)out.push({id:'DOUBLE_SWITCH',label:'Double Switch',detail:'Replace pitcher + fielder and swap their batting-order slots'})}return out}

export function beginPrePitchDecision(state:GameState,action:string):GameState {if(state.status!=='in_progress'||state.waitingFor!=='PITCH_ROLL'||state.pendingDecision)throw new Error('Manager actions are only available before the pitch roll.');const legal=new Set(getPrePitchActions(state).map(a=>a.id));if(!legal.has(action))throw new Error('That manager action is not legal right now.');const off=offenseSide(state),def=defenseSide(state)
 if(action==='NATURAL_STEAL')return nextDecision(state,{type:'NATURAL_STEAL_RUNNER_SELECTION',actingSide:off,legalActions:['SELECT_RUNNERS'],context:{eligibleAttempts:naturalStealAttempts(state)}})
 if(action==='INTENTIONAL_WALK')return nextDecision(state,{type:'INTENTIONAL_WALK_CONFIRM',actingSide:def,legalActions:['CONFIRM_INTENTIONAL_WALK'],context:{}})
 if(action==='SAC_BUNT')return nextDecision(state,{type:'SAC_BUNT_CONFIRM',actingSide:off,legalActions:['CONFIRM_SAC_BUNT'],context:{}})
 if(action==='SQUEEZE_BUNT')return nextDecision(state,{type:'SQUEEZE_BUNT_CONFIRM',actingSide:off,legalActions:['CONFIRM_SQUEEZE'],context:{}})
 if(action==='INFIELD_IN')return nextDecision(state,{type:'INFIELD_IN_CONFIRM',actingSide:def,legalActions:['CONFIRM_INFIELD_IN'],context:{}})
 if(action==='PINCH_HITTER')return nextDecision(state,{type:'PINCH_HITTER_SELECTION',actingSide:off,legalActions:['SELECT_REPLACEMENT'],context:{outgoing:state.plateAppearance.batterCardKey}})
 if(action==='PINCH_RUNNER')return nextDecision(state,{type:'PINCH_RUNNER_TARGET',actingSide:off,legalActions:['SELECT_RUNNER'],context:{}})
 if(action==='DEFENSIVE_SUB')return nextDecision(state,{type:'DEF_SUB_POSITION',actingSide:def,legalActions:['SELECT_POSITION'],context:{}})
 if(action==='PITCHING_CHANGE')return nextDecision(state,{type:'DEF_SUB_REPLACEMENT',actingSide:def,legalActions:['SELECT_REPLACEMENT'],context:{position:'P',outgoing:state.pregame[def].defensiveAlignment.P}})
 if(action==='DOUBLE_SWITCH')return nextDecision(state,{type:'DOUBLE_SWITCH_PITCHER',actingSide:def,legalActions:['SELECT_REPLACEMENT'],context:{outgoingPitcher:state.pregame[def].defensiveAlignment.P}})
 throw new Error('Unknown manager action.')}

export function getDecisionView(state:GameState):DecisionView|null{const d=state.pendingDecision;if(!d)return null
 if(d.decisionType==='EXTRA_BASE_DECISION')return{title:'Extra Base Decision',description:'Choose whether to attempt optional extra bases.',actingSide:d.actingSide,mode:'single',options:[{id:'DECLINE_EXTRA_BASES',label:'Hold Runners',detail:'End the play with automatic advancement.'},{id:'ATTEMPT_EXTRA_BASES',label:'Attempt Extra Base(s)',detail:'Select the runner(s) attempting to advance.'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(d.decisionType==='TAG_UP_DECISION')return{title:'Tag-Up Decision',description:'Choose whether to attempt to tag after the fly ball.',actingSide:d.actingSide,mode:'single',options:[{id:'HOLD_RUNNERS',label:'Hold Runners',detail:'Decline all tag-up attempts.'},{id:'ATTEMPT_TAG_UP',label:'Attempt Tag-Up',detail:'Select every runner attempting to advance.'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(['EXTRA_BASE_RUNNER_SELECTION','TAG_UP_RUNNER_SELECTION','NATURAL_STEAL_RUNNER_SELECTION'].includes(d.decisionType)){const aa=attemptsFor(state),natural=d.decisionType.startsWith('NATURAL'),tag=d.decisionType.startsWith('TAG');return{title:natural?'Select Steal Runners':tag?'Select Tag-Up Runners':'Select Extra-Base Runners',description:'Select the legal runner(s), then confirm.',actingSide:d.actingSide,mode:'multi_runner',options:aa.map(a=>({id:attemptId(a),label:formatAttempt(a),detail:`${natural?'SB':'BSR'} ${natural?(a.runner.stolenBase??10):(a.runner.baserunning??10)}${a.requiresAttemptId?' · runner ahead must also advance':''}`})),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(d.decisionType==='EXTRA_BASE_DEFENSE_TARGET'||d.decisionType==='NATURAL_STEAL_DEFENSE_TARGET'){const aa=d.context.attempts as RunnerAttempt[];const natural=d.decisionType.startsWith('NATURAL');return{title:'Select Throw Target',description:'Defense selects the one runner it will attempt to throw out.',actingSide:d.actingSide,mode:'single',options:aa.map(a=>({id:attemptId(a),label:formatAttempt(a),detail:`Target ${natural?'SB':'BSR'} ${natural?(a.runner.stolenBase??10):(a.runner.baserunning??10)}`})),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(d.decisionType==='TAG_UP_DEFENSE_SELECTION'){const aa=d.context.attempts as RunnerAttempt[],ofs=eligibleOF(state,d.actingSide);return{title:'Select Throw',description:'RTS succeeded. Select the runner and eligible outfielder.',actingSide:d.actingSide,mode:'single',options:aa.flatMap(a=>ofs.map(pos=>{const c=defenseCard(state,d.actingSide,pos);return{id:`${attemptId(a)}@@${pos}`,label:`${formatAttempt(a)} · ${pos}`,detail:`${c?.playerName??pos} · DEF ${fielding(state,d.actingSide,pos)}${a.from==='1B'&&a.to==='2B'?' · +10 for 1B→2B tag':''}`}})),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(['EXTRA_BASE_RTS','TAG_UP_RTS','OUTFIELD_FIELDING_ROLL','CATCHER_FIELDING_ROLL','ONE_BASE_PLUS_STOLEN_BASE','SECOND_STEAL_HOME_ROLL','SAC_BUNT_RTS','SAC_BUNT_WHEEL_RTS','SQUEEZE_BUNT_ROLL'].includes(d.decisionType)){const labels:Record<string,string>={EXTRA_BASE_RTS:'Extra-Base RTS',TAG_UP_RTS:'Tag-Up RTS',OUTFIELD_FIELDING_ROLL:'Outfield Fielding Check',CATCHER_FIELDING_ROLL:'Catcher Fielding Check',ONE_BASE_PLUS_STOLEN_BASE:'Mandatory 1B+ Steal',SECOND_STEAL_HOME_ROLL:'Steal Home Fielding Check',SAC_BUNT_RTS:'Sacrifice Bunt RTS',SAC_BUNT_WHEEL_RTS:'Wheel Play RTS',SQUEEZE_BUNT_ROLL:'Squeeze Bunt Roll'};return{title:labels[d.decisionType],description:'Roll the authoritative d20 and apply the Elements Rulebook result.',actingSide:d.actingSide,mode:'roll',options:[],confirmationLabel:'Roll d20',confirmationSummary:()=>''}}
 if(d.decisionType==='OUTFIELD_SELECTION'){const side=d.actingSide;return{title:'Select Outfielder',description:'Select an eligible outfielder for the throw. LF/CF/RF rotate before reuse.',actingSide:side,mode:'single',options:eligibleOF(state,side).map(pos=>{const c=defenseCard(state,side,pos);return{id:ofOptionId(pos),label:`${pos} · ${c?.playerName??pos}`,detail:`DEF ${fielding(state,side,pos)}`}}),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(d.decisionType==='INTENTIONAL_WALK_CONFIRM')return{title:'Intentional Walk',description:'Confirm the intentional walk. Once confirmed, the hitter is awarded 1B.',actingSide:d.actingSide,mode:'single',options:[{id:'CONFIRM_INTENTIONAL_WALK',label:'Issue Intentional Walk',detail:'Forced runners advance one base'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(d.decisionType==='SAC_BUNT_CONFIRM')return{title:'Sacrifice Bunt',description:'Once confirmed, the bunt declaration is irrevocable.',actingSide:d.actingSide,mode:'single',options:[{id:'CONFIRM_SAC_BUNT',label:'Declare Sacrifice Bunt',detail:'Defense will choose whether to use wheel play'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(d.decisionType==='SAC_BUNT_DEFENSE')return{title:'Defend Sacrifice Bunt',description:'Defense chooses whether to counter with wheel play.',actingSide:d.actingSide,mode:'single',options:[{id:'NO_WHEEL',label:'Standard Bunt Defense',detail:'Use the standard sacrifice bunt table'},{id:'WHEEL_PLAY',label:'Wheel Play',detail:'Use the wheel-play bunt table'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(d.decisionType==='SQUEEZE_BUNT_CONFIRM')return{title:'Squeeze Bunt',description:'Confirm the squeeze. The next action is the Rulebook squeeze roll.',actingSide:d.actingSide,mode:'single',options:[{id:'CONFIRM_SQUEEZE',label:'Declare Squeeze Bunt',detail:'Decision becomes irrevocable'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(d.decisionType==='INFIELD_IN_CONFIRM')return{title:'Infield In',description:'Lock infield-in for this plate appearance.',actingSide:d.actingSide,mode:'single',options:[{id:'CONFIRM_INFIELD_IN',label:'Bring Infield In',detail:'PU/FB become 1B; GB uses infield-in rules'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(d.decisionType==='SECOND_STEAL_HOME_DECISION')return{title:'Second Steal of Home',description:'After a successful steal of 2B with a runner on 3B, offense may attempt home.',actingSide:d.actingSide,mode:'single',options:[{id:'DECLINE_SECOND_STEAL_HOME',label:'Hold at 3B',detail:'End the steal sequence'},{id:'ATTEMPT_SECOND_STEAL_HOME',label:'Attempt Steal of Home',detail:'Defense uses full infield + catcher check'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(['PINCH_HITTER_SELECTION','DEF_SUB_REPLACEMENT','PINCH_RUNNER_REPLACEMENT','DOUBLE_SWITCH_PITCHER','DOUBLE_SWITCH_FIELDER'].includes(d.decisionType)){let cards=benchCards(state,d.actingSide);if(d.decisionType==='DOUBLE_SWITCH_FIELDER')cards=cards.filter(c=>c.cardKey!==d.context.newPitcher);const title=d.decisionType==='PINCH_HITTER_SELECTION'?'Select Pinch Hitter':d.decisionType==='PINCH_RUNNER_REPLACEMENT'?'Select Pinch Runner':d.decisionType==='DOUBLE_SWITCH_PITCHER'?'Select New Pitcher':d.decisionType==='DOUBLE_SWITCH_FIELDER'?'Select New Fielder':'Select Replacement';return{title,description:'Only unused bench players are eligible.',actingSide:d.actingSide,mode:'single',options:cards.map(c=>({id:c.cardKey,label:c.playerName,detail:`${c.year??''} · OB ${c.hitter.onBase??5} · Control ${c.pitcher.control??-5}`})),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(d.decisionType==='DOUBLE_SWITCH_OUTGOING_FIELDER'){const positions=(Object.keys(state.pregame[d.actingSide].defensiveAlignment) as DefensivePosition[]).filter(p=>p!=='P'&&p!=='DH');return{title:'Select Outgoing Fielder',description:'The new pitcher takes this fielder’s batting-order slot; the new fielder takes the old pitcher’s slot.',actingSide:d.actingSide,mode:'single',options:positions.map(p=>{const c=defenseCard(state,d.actingSide,p);return{id:p,label:`${p} · ${c?.playerName??'—'}`,detail:'Remove this fielder in the double switch'}}),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(d.decisionType==='PINCH_RUNNER_TARGET')return{title:'Select Runner to Replace',description:'Choose the existing runner for the pinch runner.',actingSide:d.actingSide,mode:'single',options:baseEntries(state).map(([base,r])=>({id:base,label:`${r.playerName} · ${base==='first'?'1B':base==='second'?'2B':'3B'}`,detail:`BSR ${r.baserunning??10} · SB ${r.stolenBase??10}`})),confirmationLabel:'Confirm',confirmationSummary:()=>''}
 if(d.decisionType==='DEF_SUB_POSITION'){const positions=(Object.keys(state.pregame[d.actingSide].defensiveAlignment) as DefensivePosition[]).filter(p=>p!=='DH');return{title:'Select Defensive Position',description:'Choose the fielder being replaced.',actingSide:d.actingSide,mode:'single',options:positions.map(p=>{const c=defenseCard(state,d.actingSide,p);return{id:p,label:`${p} · ${c?.playerName??'—'}`,detail:`DEF ${fielding(state,d.actingSide,p)}`}}),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(d.decisionType==='GROUND_BALL_RESOLUTION'){const pre=d.context.preBases as BasesState;const opts:DecisionOption[]=[];const combos=eligibleInfCombos(state,d.actingSide);if(d.context.infieldIn===true){const loaded=Boolean(pre.first&&pre.second&&pre.third);if(loaded)return{title:'Ground Ball · Infield In',description:'Bases loaded: the lead runner heading home is automatically out and all other runners advance one base.',actingSide:d.actingSide,mode:'single',options:[{id:'HOLD_RUNNERS',label:'Resolve Forced Out at Home',detail:'Lead runner out; all other runners and batter advance one base'}],confirmationLabel:'Confirm',confirmationSummary:()=>''};return{title:'Ground Ball · Infield In',description:'Offense chooses whether to accept the infield-in hold result or declare contact play.',actingSide:d.actingSide,mode:'single',options:[{id:'HOLD_RUNNERS',label:'Hold Runners',detail:'Existing runners hold unless forced; batter is out.'},{id:'CONTACT_PLAY',label:'Contact Play',detail:'All existing runners attempt to advance one base.'}],confirmationLabel:'Confirm',confirmationSummary:()=>''}}if(pre.first){opts.push({id:'TAKE_SINGULAR_OUT',label:'Take Singular Out',detail:'Resolve the Rulebook RFO to determine which forced runner is out.'});opts.push({id:'ATTEMPT_STANDARD_DBP',label:'Attempt Standard Double Play',detail:'Use an eligible INF combination for two fielding checks.'});if(pre.second&&combos.some(c=>c.includes('3B')))opts.push({id:'ATTEMPT_3B_1B_DBP',label:'Attempt 3B → 1B Double Play',detail:'First check targets the runner heading to 3B.'});const tp=pre.second&&state.outs===0&&combos.includes('1B+2B+3B')&&fielding(state,d.actingSide,'2B')>=4&&fielding(state,d.actingSide,'3B')>=2;if(tp)opts.push({id:'ATTEMPT_TRIPLE_PLAY',label:'Attempt 3B → 2B → 1B Triple Play',detail:'Three sequential Rulebook checks; later checks require earlier outs.'});return{title:'Ground Ball Resolution',description:'Select the legal Elements force-play option.',actingSide:d.actingSide,mode:'single',options:opts,confirmationLabel:'Confirm',confirmationSummary:()=>''}}return{title:'Ground Ball RFO',description:'Roll For Out determines runner advancement on this ground ball.',actingSide:d.actingSide,mode:'roll',options:[],confirmationLabel:'Roll d20',confirmationSummary:()=>''}}
 if(d.decisionType==='GB_INF_COMBO_SELECTION'){const kind=String(d.context.gbKind);let combos=eligibleInfCombos(state,d.actingSide);if(kind==='3B1B')combos=combos.filter(c=>c.includes('3B'));return{title:'Select Infield Combination',description:'A combination is consumed whether the attempt succeeds or fails and cannot repeat until the usage cycle permits it.',actingSide:d.actingSide,mode:'single',options:combos.map(c=>({id:c,label:c.replaceAll('+',' + '),detail:`Combined DEF ${comboDefense(state,d.actingSide,c)}`})),confirmationLabel:'Confirm',confirmationSummary:()=>''}}
 if(['GB_SINGULAR_RFO','GB_RUNNER_2B_RFO','GB_STANDARD_FIRST_CHECK','GB_STANDARD_SECOND_CHECK','GB_3B1B_FIRST_CHECK','GB_3B1B_SECOND_CHECK','GB_TRIPLE_FIRST_CHECK','GB_TRIPLE_SECOND_CHECK','GB_TRIPLE_THIRD_CHECK','GB_CONTACT_FIELDING_ROLL'].includes(d.decisionType)){const names:Record<string,string>={GB_SINGULAR_RFO:'Ground Ball RFO',GB_RUNNER_2B_RFO:'Runner-on-2B RFO',GB_STANDARD_FIRST_CHECK:'DBP Fielding Check · Lead Force',GB_STANDARD_SECOND_CHECK:'DBP Fielding Check · Batter',GB_3B1B_FIRST_CHECK:'3B→1B DP · First Check',GB_3B1B_SECOND_CHECK:'3B→1B DP · Batter Check',GB_TRIPLE_FIRST_CHECK:'Triple Play · Runner to 3B',GB_TRIPLE_SECOND_CHECK:'Triple Play · Runner to 2B',GB_TRIPLE_THIRD_CHECK:'Triple Play · Batter to 1B',GB_CONTACT_FIELDING_ROLL:'Contact Play · Full Infield + Catcher'};return{title:names[d.decisionType]??d.decisionType,description:'Roll the authoritative d20 and apply the exact Rulebook natural-1 / natural-20 and comparison result.',actingSide:d.actingSide,mode:'roll',options:[],confirmationLabel:'Roll d20',confirmationSummary:()=>''}}
 if(d.decisionType==='ENTRY_ATTRIBUTE_MODE')return{title:'Entry Attribute Mode',description:'Choose the locked attribute mode for this replacement appearance.',actingSide:d.actingSide,mode:'single',options:[{id:'CARD_ATTRIBUTES',label:'Use Card Attributes',detail:'Use printed card attributes/charts'},{id:'DEFAULT_ATTRIBUTES',label:'Use Default Attributes',detail:'Use Rulebook chartless/default attributes'}],confirmationLabel:'Confirm Entry',confirmationSummary:()=>''}
 return{title:d.decisionType.replaceAll('_',' '),description:'This Elements Rulebook branch is not active in this resolver update yet.',actingSide:d.actingSide,mode:'information',options:[],confirmationLabel:'Resolver Pending',confirmationSummary:()=>''}}

export function validateDecisionSelection(state:GameState,ids:string[]){const d=assertPending(state),v=getDecisionView(state);if(!v||v.mode==='information'||v.mode==='roll')throw new Error('This decision does not accept a selection.');if(!ids.length)throw new Error('Select an option before confirming.');if(v.mode==='single'&&ids.length!==1)throw new Error('Select exactly one option.');const legal=new Set(v.options.map(o=>o.id));for(const id of ids)if(!legal.has(id))throw new Error(`Illegal decision selection: ${id}`);if(v.mode==='multi_runner')for(const a of attemptsFor(state))if(ids.includes(attemptId(a))&&a.requiresAttemptId&&!ids.includes(a.requiresAttemptId))throw new Error(`${formatAttempt(a)} is not legal unless the runner ahead also advances.`);if(['EXTRA_BASE_RUNNER_SELECTION','TAG_UP_RUNNER_SELECTION','NATURAL_STEAL_RUNNER_SELECTION'].includes(d.decisionType)&&!ids.length)throw new Error('Select at least one runner.')}

function entryDecision(state:GameState,side:GameSide,context:Record<string,unknown>){return nextDecision(state,{type:'ENTRY_ATTRIBUTE_MODE',actingSide:side,legalActions:['CARD_ATTRIBUTES','DEFAULT_ATTRIBUTES'],context})}

export function confirmManagerDecision(state:GameState,ids:string[]):GameState{validateDecisionSelection(state,ids);const d=assertPending(state),action=ids[0]
 if(d.decisionType==='EXTRA_BASE_DECISION'){if(action==='DECLINE_EXTRA_BASES')return declineSimpleCoreDecision(state);const eligibleAttempts=extraAttempts(state);if(!eligibleAttempts.length)return declineSimpleCoreDecision(state);return nextDecision(state,{type:'EXTRA_BASE_RUNNER_SELECTION',actingSide:d.actingSide,legalActions:['SELECT_RUNNERS'],context:{...d.context,eligibleAttempts}})}
 if(d.decisionType==='TAG_UP_DECISION'){if(action==='HOLD_RUNNERS')return declineSimpleCoreDecision(state);const eligibleAttempts=tagAttempts(state);if(!eligibleAttempts.length)return declineSimpleCoreDecision(state);return nextDecision(state,{type:'TAG_UP_RUNNER_SELECTION',actingSide:d.actingSide,legalActions:['SELECT_RUNNERS'],context:{...d.context,eligibleAttempts}})}
 if(d.decisionType==='EXTRA_BASE_RUNNER_SELECTION'){const attempts=attemptsFor(state).filter(a=>ids.includes(attemptId(a)));return nextDecision(state,{type:'EXTRA_BASE_DEFENSE_TARGET',actingSide:other(d.actingSide),legalActions:['SELECT_THROW_TARGET'],context:{...d.context,attempts}})}
 if(d.decisionType==='TAG_UP_RUNNER_SELECTION'){const attempts=attemptsFor(state).filter(a=>ids.includes(attemptId(a)));return nextDecision(state,{type:'TAG_UP_RTS',actingSide:d.actingSide,legalActions:['ROLL_RTS'],context:{...d.context,attempts}})}
 if(d.decisionType==='EXTRA_BASE_DEFENSE_TARGET'){const attempts=d.context.attempts as RunnerAttempt[];const target=attempts.find(a=>attemptId(a)===action);if(!target)throw new Error('Selected throw target is no longer legal.');if(state.outs===2&&target.to==='HOME')return nextDecision(state,{type:'OUTFIELD_SELECTION',actingSide:d.actingSide,legalActions:['SELECT_OUTFIELDER'],context:{...d.context,target,kind:'EXTRA_BASE',rtsSkipped:true}});return nextDecision(state,{type:'EXTRA_BASE_RTS',actingSide:other(d.actingSide),legalActions:['ROLL_RTS'],context:{...d.context,target}})}
 if(d.decisionType==='TAG_UP_DEFENSE_SELECTION'){const attempts=d.context.attempts as RunnerAttempt[];const [targetId,posRaw]=action.split('@@');const pos=posRaw as OF;const target=attempts.find(a=>attemptId(a)===targetId);if(!target||!eligibleOF(state,d.actingSide).includes(pos))throw new Error('Selected tag-up throw is no longer legal.');const used=withOFUse(state,d.actingSide,pos);return nextDecision(used,{type:'OUTFIELD_FIELDING_ROLL',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,target,outfielder:pos,kind:'TAG_UP',tagOneToTwo:target.from==='1B'&&target.to==='2B'}})}
 if(d.decisionType==='OUTFIELD_SELECTION'){const pos=action.replace('OF::','') as OF;if(!eligibleOF(state,d.actingSide).includes(pos))throw new Error('That outfielder is not eligible in the current usage cycle.');const used=withOFUse(state,d.actingSide,pos);return nextDecision(used,{type:'OUTFIELD_FIELDING_ROLL',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,outfielder:pos}})}
 if(d.decisionType==='NATURAL_STEAL_RUNNER_SELECTION'){const attempts=attemptsFor(state).filter(a=>ids.includes(attemptId(a)));const def=other(d.actingSide);const catcherDef=fielding(state,def,'C');let next=state;if(catcherDef>=0)next={...next,naturalStolenBaseUsed:{away:next.naturalStolenBaseUsed?.away??false,home:next.naturalStolenBaseUsed?.home??false,[d.actingSide]:true}};if(attempts.length===1)return nextDecision(next,{type:'CATCHER_FIELDING_ROLL',actingSide:def,legalActions:['ROLL_FIELDING'],context:{attempts,target:attempts[0],kind:'NATURAL_STEAL'}});return nextDecision(next,{type:'NATURAL_STEAL_DEFENSE_TARGET',actingSide:def,legalActions:['SELECT_THROW_TARGET'],context:{attempts}})}
 if(d.decisionType==='NATURAL_STEAL_DEFENSE_TARGET'){const attempts=d.context.attempts as RunnerAttempt[];const target=attempts.find(a=>attemptId(a)===action);if(!target)throw new Error('Selected steal target is no longer legal.');return nextDecision(state,{type:'CATCHER_FIELDING_ROLL',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{attempts,target,kind:'NATURAL_STEAL'}})}
 if(d.decisionType==='INTENTIONAL_WALK_CONFIRM')return awardWalk(state)
 if(d.decisionType==='SAC_BUNT_CONFIRM')return nextDecision(state,{type:'SAC_BUNT_DEFENSE',actingSide:other(d.actingSide),legalActions:['NO_WHEEL','WHEEL_PLAY'],context:{}})
 if(d.decisionType==='SAC_BUNT_DEFENSE')return nextDecision(state,{type:action==='WHEEL_PLAY'?'SAC_BUNT_WHEEL_RTS':'SAC_BUNT_RTS',actingSide:other(d.actingSide),legalActions:['ROLL_RTS'],context:{wheel:action==='WHEEL_PLAY'}})
 if(d.decisionType==='SQUEEZE_BUNT_CONFIRM')return nextDecision(state,{type:'SQUEEZE_BUNT_ROLL',actingSide:d.actingSide,legalActions:['ROLL'],context:{}})
 if(d.decisionType==='INFIELD_IN_CONFIRM')return resumeSamePlateAppearance({...state,plateAppearance:{...state.plateAppearance,infieldIn:true}})
 if(d.decisionType==='SECOND_STEAL_HOME_DECISION'){if(action==='DECLINE_SECOND_STEAL_HOME')return resumeSamePlateAppearance({...state,pendingDecision:null,status:'in_progress'});const target=state.bases.third;if(!target)return resumeSamePlateAppearance(state);return nextDecision(state,{type:'SECOND_STEAL_HOME_ROLL',actingSide:other(d.actingSide),legalActions:['ROLL_FIELDING'],context:{target}})}
 if(d.decisionType==='PINCH_HITTER_SELECTION')return entryDecision(state,d.actingSide,{applyKind:'PINCH_HITTER',replacement:action,outgoing:d.context.outgoing})
 if(d.decisionType==='PINCH_RUNNER_TARGET'){const base=action as BaseName;const outgoing=state.bases[base]?.cardKey;if(!outgoing)throw new Error('Runner is no longer on that base.');return nextDecision(state,{type:'PINCH_RUNNER_REPLACEMENT',actingSide:d.actingSide,legalActions:['SELECT_REPLACEMENT'],context:{base,outgoing}})}
 if(d.decisionType==='PINCH_RUNNER_REPLACEMENT')return entryDecision(state,d.actingSide,{applyKind:'PINCH_RUNNER',replacement:action,outgoing:d.context.outgoing,base:d.context.base})
 if(d.decisionType==='DEF_SUB_POSITION'){const position=action as DefensivePosition;return nextDecision(state,{type:'DEF_SUB_REPLACEMENT',actingSide:d.actingSide,legalActions:['SELECT_REPLACEMENT'],context:{position,outgoing:state.pregame[d.actingSide].defensiveAlignment[position]}})}
 if(d.decisionType==='DEF_SUB_REPLACEMENT')return entryDecision(state,d.actingSide,{applyKind:'DEFENSIVE_SUB',replacement:action,outgoing:d.context.outgoing,position:d.context.position})
 if(d.decisionType==='DOUBLE_SWITCH_PITCHER')return nextDecision(state,{type:'DOUBLE_SWITCH_FIELDER',actingSide:d.actingSide,legalActions:['SELECT_REPLACEMENT'],context:{...d.context,newPitcher:action}})
 if(d.decisionType==='DOUBLE_SWITCH_FIELDER')return nextDecision(state,{type:'DOUBLE_SWITCH_OUTGOING_FIELDER',actingSide:d.actingSide,legalActions:['SELECT_POSITION'],context:{...d.context,newFielder:action}})
 if(d.decisionType==='DOUBLE_SWITCH_OUTGOING_FIELDER')return entryDecision(state,d.actingSide,{applyKind:'DOUBLE_SWITCH',newPitcher:d.context.newPitcher,newFielder:d.context.newFielder,outgoingPitcher:d.context.outgoingPitcher,outgoingFielder:state.pregame[d.actingSide].defensiveAlignment[action as DefensivePosition],outgoingPosition:action})
 if(d.decisionType==='GROUND_BALL_RESOLUTION'){const pre=d.context.preBases as BasesState;if(d.context.infieldIn===true){if(action==='CONTACT_PLAY')return nextDecision(state,{type:'GB_CONTACT_FIELDING_ROLL',actingSide:other(d.actingSide),legalActions:['ROLL_FIELDING'],context:d.context});const batter=gbBatterRunner(state);let runs=0;let bases: BasesState={first:pre.first,second:pre.second,third:pre.third};if(pre.first&&pre.second&&pre.third){bases={first:batter,second:pre.first,third:pre.second};return gbFinish(state,bases,state.outs+1,0)}return gbFinish(state,bases,state.outs+1,runs)}if(action==='TAKE_SINGULAR_OUT')return nextDecision(state,{type:'GB_SINGULAR_RFO',actingSide:d.actingSide,legalActions:['ROLL_RFO'],context:d.context});if(action==='ATTEMPT_STANDARD_DBP')return nextDecision(state,{type:'GB_INF_COMBO_SELECTION',actingSide:d.actingSide,legalActions:['SELECT_COMBO'],context:{...d.context,gbKind:'STANDARD'}});if(action==='ATTEMPT_3B_1B_DBP')return nextDecision(state,{type:'GB_INF_COMBO_SELECTION',actingSide:d.actingSide,legalActions:['SELECT_COMBO'],context:{...d.context,gbKind:'3B1B'}});if(action==='ATTEMPT_TRIPLE_PLAY'){const combo:INFCombo='1B+2B+3B';if(!eligibleInfCombos(state,d.actingSide).includes(combo))throw new Error('Triple-play infield combination is not eligible.');const used=withInfUse(state,d.actingSide,combo);return nextDecision(used,{type:'GB_TRIPLE_FIRST_CHECK',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,combo}})}}
 if(d.decisionType==='GB_INF_COMBO_SELECTION'){const combo=action as INFCombo;if(!eligibleInfCombos(state,d.actingSide).includes(combo))throw new Error('That infield combination is not eligible in the current usage cycle.');const used=withInfUse(state,d.actingSide,combo);return nextDecision(used,{type:String(d.context.gbKind)==='3B1B'?'GB_3B1B_FIRST_CHECK':'GB_STANDARD_FIRST_CHECK',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,combo}})}
 if(d.decisionType==='ENTRY_ATTRIBUTE_MODE'){const replacement=String(d.context.replacement),outgoing=String(d.context.outgoing),useDefault=action==='DEFAULT_ATTRIBUTES';let next:GameState=applyEntryMode(state,d.actingSide,replacement,useDefault);const kind=String(d.context.applyKind);if(kind==='PINCH_HITTER')next=replacePlayerEverywhere(next,d.actingSide,outgoing,replacement);else if(kind==='PINCH_RUNNER')next=replacePlayerEverywhere(next,d.actingSide,outgoing,replacement,d.context.base as BaseName);else if(kind==='DEFENSIVE_SUB')next=replacePlayerEverywhere(next,d.actingSide,outgoing,replacement);else if(kind==='DOUBLE_SWITCH'){const newPitcher=String(d.context.newPitcher),newFielder=String(d.context.newFielder),oldPitcher=String(d.context.outgoingPitcher),oldFielder=String(d.context.outgoingFielder),pos=d.context.outgoingPosition as DefensivePosition;next=applyEntryMode(next,d.actingSide,newPitcher,useDefault);next=applyEntryMode(next,d.actingSide,newFielder,useDefault);const pre={...next.pregame[d.actingSide],battingOrderCardKeys:[...next.pregame[d.actingSide].battingOrderCardKeys],defensiveAlignment:{...next.pregame[d.actingSide].defensiveAlignment}};const pSlot=pre.battingOrderCardKeys.indexOf(oldPitcher),fSlot=pre.battingOrderCardKeys.indexOf(oldFielder);if(pre.battingOrderCardKeys.includes(newPitcher)||pre.battingOrderCardKeys.includes(newFielder))throw new Error('Double-switch replacement is already active in the batting order.');if(pSlot>=0&&fSlot>=0&&pSlot===fSlot)throw new Error('Double switch requires two distinct batting-order slots.');if(pSlot>=0)pre.battingOrderCardKeys[pSlot]=newFielder;if(fSlot>=0)pre.battingOrderCardKeys[fSlot]=newPitcher;assertUniqueLineup(pre.battingOrderCardKeys);pre.defensiveAlignment.P=newPitcher;pre.defensiveAlignment[pos]=newFielder;next={...next,pregame:{...next.pregame,[d.actingSide]:pre},plateAppearance:{...next.plateAppearance,pitcherCardKey:next.plateAppearance.pitcherCardKey===oldPitcher?newPitcher:next.plateAppearance.pitcherCardKey,batterCardKey:next.plateAppearance.batterCardKey===oldPitcher?newFielder:next.plateAppearance.batterCardKey===oldFielder?newPitcher:next.plateAppearance.batterCardKey}}}return resumeSamePlateAppearance(next)}
 throw new Error(`Decision resolver for ${d.decisionType} is not active yet.`)}

function moveSuccessfulAttempts(state:GameState,attempts:RunnerAttempt[],target:RunnerAttempt,targetOut:boolean):GameState{let next={...state,bases:{...state.bases},score:{...state.score}};const offense=offenseSide(state);let outs=state.outs;const remove=(key:string)=>removeRunner(next.bases,key);for(const a of attempts){const isTarget=attemptId(a)===attemptId(target);if(isTarget&&targetOut){outs=Math.min(3,outs+1) as 0|1|2|3;remove(a.runner.cardKey);continue}if(outs>=3)break;remove(a.runner.cardKey);if(a.to==='HOME')next.score[offense]++;else if(a.to==='3B')placeRunner(next.bases,'third',a.runner);else placeRunner(next.bases,'second',a.runner)}next.outs=outs;return next}
function moveSteals(state:GameState,attempts:RunnerAttempt[],target:RunnerAttempt,targetOut:boolean):GameState{let next={...state,bases:{...state.bases},score:{...state.score}};const offense=offenseSide(state);const outsBefore=state.outs;if(targetOut){next.outs=Math.min(3,next.outs+1) as 0|1|2|3;removeRunner(next.bases,target.runner.cardKey);if(outsBefore===2)return next}for(const a of attempts){if(attemptId(a)===attemptId(target)&&targetOut)continue;removeRunner(next.bases,a.runner.cardKey);if(a.to==='HOME')next.score[offense]++;else if(a.to==='3B')placeRunner(next.bases,'third',a.runner);else placeRunner(next.bases,'second',a.runner)}return next}
function finishOrResumeAfterSteal(state:GameState,attempts:RunnerAttempt[],targetOut:boolean):GameState{if(state.outs>=3)return finishWithoutPlateAppearance(state);const stoleSecond=attempts.some(a=>a.from==='1B'&&a.to==='2B')&&!targetOut;const offense=offenseSide(state);if(stoleSecond&&state.bases.third)return nextDecision(state,{type:'SECOND_STEAL_HOME_DECISION',actingSide:offense,legalActions:['DECLINE_SECOND_STEAL_HOME','ATTEMPT_SECOND_STEAL_HOME'],context:{}});return resumeSamePlateAppearance(state)}
function fullInfieldCatcherDefense(state:GameState,side:GameSide){return (['C','1B','2B','3B','SS'] as DefensivePosition[]).reduce((sum,p)=>sum+fielding(state,side,p),0)}

function gbBatterRunner(state:GameState):BaseRunnerState{const side=offenseSide(state);const card=cardFor(state,side,state.plateAppearance.batterCardKey);if(!card)throw new Error('Ground-ball batter is unavailable.');return runnerFromCard(card,state.pregame[side].defaultBatterCardKeys.includes(card.cardKey)||card.hitter.onBase===null)}
function gbFinish(state:GameState,bases:BasesState,outs:number,runCount=0):GameState{let next:GameState={...state,bases,outs:Math.min(3,outs) as 0|1|2|3,pendingDecision:null,status:'in_progress'};if(runCount&&next.outs<3)next=score(next,offenseSide(state),runCount);return finishPlateAppearance(next)}
function gbAllSafeAdvance(state:GameState,pre:BasesState):GameState{const batter=gbBatterRunner(state);const runs=pre.third?1:0;const bases:BasesState={first:batter,second:pre.first,third:pre.second};return gbFinish(state,bases,state.outs,runs)}
function gbStandardFinalize(state:GameState,firstOut:boolean,secondOut:boolean):GameState{const pre=state.pendingDecision?.context.preBases as BasesState;const batter=gbBatterRunner(state);const outs=state.outs+(firstOut?1:0)+(secondOut?1:0);if(outs>=3)return gbFinish(state,{first:null,second:null,third:null},outs,0);const bases:BasesState={first:secondOut?null:batter,second:firstOut?null:pre.first,third:pre.second};return gbFinish(state,bases,outs,pre.third?1:0)}
function gbThreeToOneFinalize(state:GameState,leadOut:boolean,batterOut:boolean):GameState{const pre=state.pendingDecision?.context.preBases as BasesState;const batter=gbBatterRunner(state);const outs=state.outs+(leadOut?1:0)+(batterOut?1:0);if(outs>=3)return gbFinish(state,{first:null,second:null,third:null},outs,0);const bases:BasesState={first:batterOut?null:batter,second:pre.first,third:leadOut?null:pre.second};return gbFinish(state,bases,outs,pre.third?1:0)}
function gbTripleFinalize(state:GameState,out3:boolean,out2:boolean,out1:boolean):GameState{const pre=state.pendingDecision?.context.preBases as BasesState;const batter=gbBatterRunner(state);const outs=state.outs+[out3,out2,out1].filter(Boolean).length;if(outs>=3)return gbFinish(state,{first:null,second:null,third:null},outs,0);return gbFinish(state,{first:out1?null:batter,second:out2?null:pre.first,third:out3?null:pre.second},outs,pre.third?1:0)}
function gbSingularResolve(state:GameState,roll:number):GameState{const pre=state.pendingDecision?.context.preBases as BasesState;const batter=gbBatterRunner(state);const outKind=pre.first&&pre.second?(roll<=5?'BATTER':roll<=15?'TO2':'TO3'):(roll<=5?'BATTER':'TO2');const outs=state.outs+1;if(outs>=3)return gbFinish(state,{first:null,second:null,third:null},outs,0);const bases:BasesState={first:outKind==='BATTER'?null:batter,second:outKind==='TO2'?null:pre.first,third:pre.second};let runs=pre.third?1:0;if(pre.second)bases.third=outKind==='TO3'?null:pre.second;else if(pre.third)bases.third=null;return gbFinish(state,bases,outs,runs)}
function gbRunner2Resolve(state:GameState,roll:number):GameState{const pre=state.pendingDecision?.context.preBases as BasesState;const outs=state.outs+1;if(outs>=3)return gbFinish(state,{first:null,second:null,third:null},outs,0);const bases:BasesState={first:null,second:roll<=10?null:pre.second,third:roll<=10?pre.second:null};return gbFinish(state,bases,outs,pre.third?1:0)}
function gbContactResolve(state:GameState,roll:number):GameState{const pre=state.pendingDecision?.context.preBases as BasesState;const lead=pre.third??pre.second??pre.first;if(!lead)return gbFinish(state,state.bases,state.outs+1);const total=roll+fullInfieldCatcherDefense(state,defenseSide(state));const out=fieldingCheckIsOut(roll,total,lead.baserunning??10);const batter=gbBatterRunner(state);const outs=state.outs+(out?1:0);if(outs>=3)return gbFinish(state,{first:null,second:null,third:null},outs,0);let runs=0;const bases:BasesState={first:batter,second:null,third:null};if(pre.first&&pre.first.cardKey!==lead.cardKey)bases.second=pre.first;if(pre.second&&pre.second.cardKey!==lead.cardKey)bases.third=pre.second;if(pre.third){if(pre.third.cardKey===lead.cardKey){if(!out)runs++}else runs++}if(pre.second&&pre.second.cardKey===lead.cardKey&&!out)bases.third=pre.second;if(pre.first&&pre.first.cardKey===lead.cardKey&&!out)bases.second=pre.first;return gbFinish(state,bases,outs,runs)}

export function resolveDecisionRoll(state:GameState,roll:number):GameState{if(!Number.isInteger(roll)||roll<1||roll>20)throw new Error('d20 roll must be 1-20.');const d=assertPending(state)
 if(d.decisionType==='EXTRA_BASE_RTS'){const attempts=d.context.attempts as RunnerAttempt[],target=d.context.target as RunnerAttempt;if(!extraBaseRtsPasses(roll))return finishPlateAppearance({...state,status:'in_progress',pendingDecision:null});return nextDecision(state,{type:'OUTFIELD_SELECTION',actingSide:other(d.actingSide),legalActions:['SELECT_OUTFIELDER'],context:{...d.context,attempts,target,kind:'EXTRA_BASE'}})}
 if(d.decisionType==='TAG_UP_RTS'){const attempts=d.context.attempts as RunnerAttempt[];if(!tagUpRtsPasses(roll,attempts))return finishPlateAppearance({...state,status:'in_progress',pendingDecision:null});return nextDecision(state,{type:'TAG_UP_DEFENSE_SELECTION',actingSide:other(d.actingSide),legalActions:['SELECT_THROW_TARGET'],context:{...d.context,attempts}})}
 if(d.decisionType==='OUTFIELD_FIELDING_ROLL'){const attempts=d.context.attempts as RunnerAttempt[],target=d.context.target as RunnerAttempt,pos=d.context.outfielder as OF,kind=String(d.context.kind??'');const side=d.actingSide,def=fielding(state,side,pos);const baseBsr=target.runner.baserunning??10;const bsr=kind==='EXTRA_BASE'?extraBaseEffectiveBaserunning(baseBsr,target.from,target.to,state.outs):tagUpEffectiveBaserunning(baseBsr);const bonus=kind==='TAG_UP'?tagUpOutfieldBonus(target.from,target.to):0;const total=roll+def+bonus;const out=fieldingCheckIsOut(roll,total,bsr);const moved=moveSuccessfulAttempts(state,attempts,target,out);return finishPlateAppearance({...moved,status:'in_progress',pendingDecision:null})}
 if(d.decisionType==='CATCHER_FIELDING_ROLL'){const attempts=d.context.attempts as RunnerAttempt[],target=d.context.target as RunnerAttempt,defSide=d.actingSide;const catcherDef=fielding(state,defSide,'C');const sb=target.runner.stolenBase??10;const out=catcherStealCheckIsOut(roll,catcherDef,sb,target.to==='HOME');const moved=moveSteals(state,attempts,target,out);return finishOrResumeAfterSteal({...moved,status:'in_progress',pendingDecision:null},attempts,out)}
 if(d.decisionType==='ONE_BASE_PLUS_STOLEN_BASE'){const target=d.context.target as BaseRunnerState;let next:GameState={...state,bases:{...state.bases},pendingDecision:null,status:'in_progress'};const sb=target?.stolenBase??10;const out=catcherStealCheckIsOut(roll,fielding(state,d.actingSide,'C'),sb,false);if(target)removeRunner(next.bases,target.cardKey);if(out)next.outs=Math.min(3,next.outs+1) as 0|1|2|3;else if(target)placeRunner(next.bases,'second',target);return finishPlateAppearance(next)}
 if(d.decisionType==='SECOND_STEAL_HOME_ROLL'){const target=d.context.target as BaseRunnerState;const total=roll+fullInfieldCatcherDefense(state,d.actingSide);const sb=target.stolenBase??10;const out=fieldingCheckIsOut(roll,total,sb);let next:GameState={...state,bases:{...state.bases},pendingDecision:null,status:'in_progress'};removeRunner(next.bases,target.cardKey);if(out)next.outs=Math.min(3,next.outs+1) as 0|1|2|3;else next=score(next,offenseSide(state));return next.outs>=3?finishWithoutPlateAppearance(next):resumeSamePlateAppearance(next)}
 if(d.decisionType==='SAC_BUNT_WHEEL_RTS'){if(roll<=15)return advanceForcedOne(state,true,false);const lead=leadRunner(state);let next:GameState={...state,bases:{...state.bases},outs:Math.min(3,state.outs+1) as 0|1|2|3};if(lead)removeRunner(next.bases,lead.cardKey);return advanceForcedOne(next,true,false)}
 if(d.decisionType==='SAC_BUNT_RTS'){if(roll<=2)return resumeSwingOnPitcherChart(state);if(roll<=4)return finishPlateAppearance({...state,status:'in_progress',pendingDecision:null,outs:Math.min(3,state.outs+1) as 0|1|2|3});if(roll===5){const lead=leadRunner(state);let next:GameState={...state,bases:{...state.bases},outs:Math.min(3,state.outs+1) as 0|1|2|3};if(lead)removeRunner(next.bases,lead.cardKey);return advanceForcedOne(next,true,false)}return advanceForcedOne(state,false,true,state.bases.first!==null&&state.bases.third!==null&&state.bases.second===null)}
 if(d.decisionType==='GB_SINGULAR_RFO')return gbSingularResolve(state,roll)
 if(d.decisionType==='GB_RUNNER_2B_RFO')return gbRunner2Resolve(state,roll)
 if(d.decisionType==='GB_CONTACT_FIELDING_ROLL')return gbContactResolve(state,roll)
 if(d.decisionType==='GB_STANDARD_FIRST_CHECK'){const pre=d.context.preBases as BasesState,combo=d.context.combo as INFCombo,target=pre.first;if(!target)throw new Error('Standard DBP requires runner heading to 2B.');if(roll===1)return gbAllSafeAdvance(state,pre);if(roll===20)return gbStandardFinalize(state,true,true);const out=fieldingCheckIsOut(roll,roll+comboDefense(state,d.actingSide,combo),target.baserunning??10);return nextDecision(state,{type:'GB_STANDARD_SECOND_CHECK',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,firstOut:out}})}
 if(d.decisionType==='GB_STANDARD_SECOND_CHECK'){const combo=d.context.combo as INFCombo,batter=gbBatterRunner(state),firstOut=Boolean(d.context.firstOut);const out=fieldingCheckIsOut(roll,roll+comboDefense(state,d.actingSide,combo),batter.baserunning??10);return gbStandardFinalize(state,firstOut,out)}
 if(d.decisionType==='GB_3B1B_FIRST_CHECK'){const pre=d.context.preBases as BasesState,combo=d.context.combo as INFCombo,target=pre.second;if(!target)throw new Error('3B→1B DP requires runner heading to 3B.');if(roll===1)return gbAllSafeAdvance(state,pre);if(roll===20)return gbThreeToOneFinalize(state,true,true);const out=fieldingCheckIsOut(roll,roll+comboDefense(state,d.actingSide,combo),target.baserunning??10);return nextDecision(state,{type:'GB_3B1B_SECOND_CHECK',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,leadOut:out}})}
 if(d.decisionType==='GB_3B1B_SECOND_CHECK'){const combo=d.context.combo as INFCombo,batter=gbBatterRunner(state),leadOut=Boolean(d.context.leadOut);const out=fieldingCheckIsOut(roll,roll+comboDefense(state,d.actingSide,combo),batter.baserunning??10);return gbThreeToOneFinalize(state,leadOut,out)}
 if(d.decisionType==='GB_TRIPLE_FIRST_CHECK'){const pre=d.context.preBases as BasesState,target=pre.second;if(!target)throw new Error('Triple play requires runner heading to 3B.');if(roll===1)return gbAllSafeAdvance(state,pre);const out=fieldingCheckIsOut(roll,roll,target.baserunning??10);if(!out)return gbTripleFinalize(state,false,false,false);if(roll===20)return gbTripleFinalize(state,true,true,true);return nextDecision(state,{type:'GB_TRIPLE_SECOND_CHECK',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,out3:true}})}
 if(d.decisionType==='GB_TRIPLE_SECOND_CHECK'){const pre=d.context.preBases as BasesState,target=pre.first;if(!target)throw new Error('Triple play requires runner heading to 2B.');if(roll===1)return gbTripleFinalize(state,true,false,false);const out=fieldingCheckIsOut(roll,roll,target.baserunning??10);if(!out)return gbTripleFinalize(state,true,false,false);if(roll===20)return gbTripleFinalize(state,true,true,true);return nextDecision(state,{type:'GB_TRIPLE_THIRD_CHECK',actingSide:d.actingSide,legalActions:['ROLL_FIELDING'],context:{...d.context,out3:true,out2:true}})}
 if(d.decisionType==='GB_TRIPLE_THIRD_CHECK'){const batter=gbBatterRunner(state);const out=fieldingCheckIsOut(roll,roll,batter.baserunning??10);return gbTripleFinalize(state,true,true,out)}
 if(d.decisionType==='SQUEEZE_BUNT_ROLL'){const side=offenseSide(state),r3=state.bases.third;if(!r3)return resumeSamePlateAppearance(state);let next:GameState={...state,bases:{...state.bases},pendingDecision:null,status:'in_progress'};if(roll<=7){removeRunner(next.bases,r3.cardKey);next.outs=Math.min(3,next.outs+1) as 0|1|2|3;return next.outs>=3?finishPlateAppearance(next):resumeSamePlateAppearance(next)}if(roll<=15){removeRunner(next.bases,r3.cardKey);next.outs=Math.min(3,next.outs+1) as 0|1|2|3;return advanceForcedOne(next,true,false)}if(roll<=19){removeRunner(next.bases,r3.cardKey);next=score(next,side);next.outs=Math.min(3,next.outs+1) as 0|1|2|3;return finishPlateAppearance(next)}removeRunner(next.bases,r3.cardKey);next=score(next,side);return advanceForcedOne(next,true,false)}
 throw new Error(`Roll resolver for ${d.decisionType} is not active yet.`)}
