import type { BaseRunnerState, BasesState, GameState } from './types'
import { gbLegalChoices,infieldCheckOut,resolveAutoOut,resolveContactPlay,resolveStandardDp,resolveThirdToFirstDp,resolveTriplePlay } from './groundBallEngine'
import type { ScenarioReport,ScenarioResult } from './scenarioHarness'
const r=(key:string,bsr=10):BaseRunnerState=>({cardKey:key,playerName:key,baserunning:bsr,stolenBase:10})
const bases=(f=false,s=false,t=false):BasesState=>({first:f?r('R1',12):null,second:s?r('R2',13):null,third:t?r('R3',14):null})
export function runGroundBallScenarioMatrix(_initial:GameState):ScenarioReport{
 const results:ScenarioResult[]=[];const test=(id:string,category:string,description:string,fn:()=>void)=>{try{fn();results.push({id,category,description,passed:true,detail:'Expected Rulebook result matched.'})}catch(e){results.push({id,category,description,passed:false,detail:e instanceof Error?e.message:String(e)})}};const a=(c:unknown,m:string)=>{if(!c)throw new Error(m)};const st=(b:BasesState,outs:0|1=0,infieldIn=false)=>({outs,bases:b,batter:r('BAT',11),infieldIn})
 for(const [roll,def,bsr,out] of [[1,99,1,false],[20,-99,99,true],[10,2,12,false],[11,2,12,true]] as const)test(`GB-CHECK-${roll}-${def}`,'GB fielding assertions',`Fielding check ${roll}+${def} vs ${bsr}`,()=>a(infieldCheckOut(roll,def,bsr)===out,'Incorrect natural/equality fielding result.'))
 test('GB-EMPTY','GB basic states','Bases empty GB = batter out',()=>{const x=resolveAutoOut(st(bases()),10);a(x.outsAdded===1&&!x.bases.first,'Expected batter out.')})
 for(const o of [0,1] as const){test(`GB-1B-AUTO-LOW-${o}`,'GB automatic out','Runner 1B RFO 1-5: batter out, runner to 2B',()=>{const x=resolveAutoOut(st(bases(true),o),5);a(x.outsAdded===1&&x.bases.second?.cardKey==='R1'&&!x.bases.first,'Wrong RFO 1-5 state.')});test(`GB-1B-AUTO-HIGH-${o}`,'GB automatic out','Runner 1B RFO 6-20: force runner out, batter safe',()=>{const x=resolveAutoOut(st(bases(true),o),6);a(x.outsAdded===1&&x.bases.first?.cardKey==='BAT'&&!x.bases.second,'Wrong RFO 6-20 state.')})}
 for(const roll of [1,5,6,15,16,20])test(`GB-12-RFO-${roll}`,'GB automatic out',`1B/2B automatic-out RFO boundary ${roll}`,()=>{const x=resolveAutoOut(st(bases(true,true)),roll);a(x.outsAdded===1,'Must record exactly one out.');a(new Set([x.bases.first?.cardKey,x.bases.second?.cardKey,x.bases.third?.cardKey].filter(Boolean)).size===[x.bases.first,x.bases.second,x.bases.third].filter(Boolean).length,'Duplicate runner.')})
 test('GB-2B-RTH-10','GB runner 2B','2B only RTH 1-10 advances runner to 3B and batter out',()=>{const x=resolveAutoOut(st(bases(false,true)),10);a(x.bases.third?.cardKey==='R2'&&x.outsAdded===1,'Expected R2 on 3B.')})
 test('GB-2B-RTH-11','GB runner 2B','2B only RTH 11-20 holds runner and batter out',()=>{const x=resolveAutoOut(st(bases(false,true)),11);a(x.bases.second?.cardKey==='R2'&&x.outsAdded===1,'Expected R2 hold.')})
 test('GB-3B-SCORE','GB runner 3B','3B only, INF IN off: runner scores and batter out',()=>{const x=resolveAutoOut(st(bases(false,false,true)),10);a(x.runs===1&&x.outsAdded===1&&!x.bases.third,'Expected run and batter out.')})
 for(const rr of [1,20])test(`DP-NAT-${rr}`,'Standard DBP',`Standard DP natural ${rr}`,()=>{const x=resolveStandardDp(st(bases(true)),0,rr);a(rr===1?x.outsAdded===0:x.outsAdded===2,'Natural override failed.')})
 test('DP-FIRST-OUT-SECOND-SAFE','Standard DBP','Each base resolves independently: 13+9 > BSR14 at 2B, but 2+9 < BSR15 at 1B',()=>{const state={outs:0 as const,bases:{first:r('R1',14),second:null,third:null},batter:r('BAT',15),infieldIn:false};const x=resolveStandardDp(state,9,13,2);a(x.outsAdded===1&&x.bases.first?.cardKey==='BAT'&&!x.bases.second,'Expected force out at 2B and batter safe at 1B.')})
 test('DP-FIRST-SAFE-SECOND-OUT','Standard DBP','Force runner safe, batter out',()=>{const x=resolveStandardDp(st(bases(true)),0,10,20);a(x.outsAdded===1&&!x.bases.first&&x.bases.second?.cardKey==='R1','Expected force runner safe/batter out.')})
 test('DP-BOTH-OUT','Standard DBP','Both ordinary fielding checks succeed',()=>{const x=resolveStandardDp(st(bases(true)),10,10,10);a(x.outsAdded===2,'Expected double play.')})
 test('DP-EQUALITY-SAFE','Standard DBP','Equality is safe',()=>{const x=resolveStandardDp(st(bases(true)),2,10,9);a(x.outsAdded===0,'Lead: 10+2 = BSR12 must be safe; batter: 9+2 = BSR11 must also be safe.')})
 test('31DP-NAT1','3B→1B DBP','Natural 1 first check makes all safe',()=>a(resolveThirdToFirstDp(st(bases(true,true)),0,1).outsAdded===0,'All should be safe.'))
 test('31DP-NAT20','3B→1B DBP','Natural 20 first check creates automatic two outs',()=>a(resolveThirdToFirstDp(st(bases(true,true)),0,20).outsAdded===2,'Expected two outs.'))
 test('31DP-ORD','3B→1B DBP','Two successful ordinary checks create two outs',()=>a(resolveThirdToFirstDp(st(bases(true,true)),10,10,10).outsAdded===2,'Expected two outs.'))
 test('TP-ELIGIBLE','Triple play','Triple play offered only at 0 outs with 1B/2B',()=>a(gbLegalChoices(st(bases(true,true),0)).includes('TRIPLE_PLAY'),'TP should be legal.'))
 test('TP-INELIGIBLE-1OUT','Triple play','Triple play unavailable with 1 out',()=>a(!gbLegalChoices(st(bases(true,true),1)).includes('TRIPLE_PLAY'),'TP must be illegal.'))
 test('TP-NAT1','Triple play','First natural 1 = all safe',()=>a(resolveTriplePlay(st(bases(true,true)),1).outsAdded===0,'All safe expected.'))
 test('TP-NAT20','Triple play','First natural 20 = automatic triple play',()=>a(resolveTriplePlay(st(bases(true,true)),20).outsAdded===3,'Three outs expected.'))
 test('TP-FIRST-FAIL','Triple play','Failed first check makes subsequent runners automatically safe',()=>a(resolveTriplePlay(st(bases(true,true)),10).outsAdded===0,'Expected no outs.'))
 test('TP-SECOND-FAIL','Triple play','Successful first then failed second stops chain',()=>a(resolveTriplePlay(st(bases(true,true)),20).outsAdded===3,'Natural 20 override regression.'))
 test('INF-LOADED','INF IN ground balls','Bases loaded GB: lead runner home automatically out; others advance; hitter safe',()=>{const x=resolveAutoOut(st(bases(true,true,true),0,true),10);a(x.outsAdded===1&&x.bases.first?.cardKey==='BAT'&&x.bases.second?.cardKey==='R1'&&x.bases.third?.cardKey==='R2','Wrong loaded INF IN state.')})
 test('INF-13','INF IN ground balls','1B/3B: existing runners hold unless forced; hitter out',()=>{const x=resolveAutoOut(st(bases(true,false,true),0,true),10);a(x.outsAdded===1&&x.bases.first?.cardKey==='R1'&&x.bases.third?.cardKey==='R3','Runners should hold.')})
 test('INF-2','INF IN ground balls','2B only: runner holds; hitter out',()=>{const x=resolveAutoOut(st(bases(false,true),0,true),10);a(x.outsAdded===1&&x.bases.second?.cardKey==='R2','Runner should hold.')})
 test('INF-CONTACT-NAT1','Contact play','Contact play natural 1 = lead safe, all advance, hitter safe',()=>{const x=resolveContactPlay(st(bases(true,true,true),0,true),99,1);a(x.outsAdded===0&&x.runs===1&&x.bases.first?.cardKey==='BAT','All-safe contact play failed.')})
 test('INF-CONTACT-NAT20','Contact play','Contact play natural 20 = lead out, other runners advance, hitter safe',()=>{const x=resolveContactPlay(st(bases(true,true,true),0,true),-99,20);a(x.outsAdded===1&&x.runs===0&&x.bases.first?.cardKey==='BAT','Lead-out contact play failed.')})
 test('NEG-DP-NO1B','Illegal GB actions','Standard DP unavailable without runner on 1B',()=>a(!gbLegalChoices(st(bases(false,true))).includes('STANDARD_DP'),'DP should be illegal.'))
 test('NEG-31-NO2B','Illegal GB actions','3B→1B DP unavailable without runner on 2B',()=>a(!gbLegalChoices(st(bases(true))).includes('THIRD_TO_FIRST_DP'),'3B→1B should be illegal.'))
 test('NEG-CONTACT-NOIN','Illegal GB actions','Contact play unavailable unless INF IN',()=>a(!gbLegalChoices(st(bases(false,false,true))).includes('CONTACT_PLAY'),'Contact should be illegal.'))
 const categories:ScenarioReport['categories']={};for(const x of results){const c=categories[x.category]??{total:0,passed:0};c.total++;if(x.passed)c.passed++;categories[x.category]=c}return{total:results.length,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,categories,results}
}
