import { beginPrePitchDecision, confirmManagerDecision, getDecisionView, getPrePitchActions, resolveDecisionRoll, noWheelSacBuntOutcome, validateDecisionSelection, type RunnerAttempt } from './decisionEngine'
import { catcherStealCheckIsOut, extraBaseEffectiveBaserunning, fieldingCheckIsOut, tagUpEffectiveBaserunning, tagUpOutfieldBonus, tagUpRtsThreshold } from './ruleAssertions'
import type { BaseRunnerState, GameSide, GameState, PendingDecision } from './types'
import { resolveCoreResult } from './coreGame'
import { effectiveCurrentPitcherControl } from './engine'
import { pitcherInstanceKey } from './pitcherStateKey'

export type ScenarioResult={id:string;category:string;description:string;passed:boolean;detail:string}
export type ScenarioReport={total:number;passed:number;failed:number;categories:Record<string,{total:number;passed:number}>;results:ScenarioResult[]}

type TestFn=()=>void
function assert(condition:unknown,message:string):asserts condition { if(!condition) throw new Error(message) }
function expectThrow(fn:()=>unknown,message:string){let threw=false;try{fn()}catch{threw=true}assert(threw,message)}

const offense=(s:GameState):GameSide=>s.half==='top'?'away':'home'
const defense=(s:GameState):GameSide=>offense(s)==='away'?'home':'away'
function runner(key:string,name:string,bsr=14,sb=12):BaseRunnerState{return{cardKey:key,playerName:name,baserunning:bsr,stolenBase:sb}}
function fixture(initial:GameState):GameState {
  const s=structuredClone(initial)
  if(s.status==='paused')s.status='in_progress'
  s.status='in_progress';s.waitingFor='PITCH_ROLL';s.pendingDecision=null;s.nextActor=defense(s);s.inning=5;s.half='top';s.outs=0;s.score={away:0,home:0};s.bases={first:null,second:null,third:null};s.naturalStolenBaseUsed={away:false,home:false};s.outfieldThrowUsage={away:{LF:0,CF:0,RF:0},home:{LF:0,CF:0,RF:0}}
  const off=offense(s),def=defense(s)
  const batter=s.pregame[off].battingOrderCardKeys[0]??Object.keys(s.pregame[off].roster?.cards??{})[0]??null
  const pitcher=s.pregame[def].defensiveAlignment.P??s.pregame[def].startingPitcherCardKey
  s.plateAppearance={batterCardKey:batter,pitcherCardKey:pitcher,pitchRoll:null,pitchTotal:null,advantage:null,swingRoll:null,chartResult:null,infieldIn:false}
  return s
}
function pending(state:GameState,type:string,actingSide:GameSide,context:Record<string,unknown>):GameState {
  const d:PendingDecision={id:`scenario-${type}`,ruleCondition:'RC5_CONDITIONAL_GAME_STATE',decisionType:type,actingSide,legalActions:[],context,createdAt:'2026-01-01T00:00:00.000Z'}
  return {...state,status:'awaiting_decision',waitingFor:'CONDITIONAL_DECISION',nextActor:actingSide,pendingDecision:d}
}
function firstOf<T>(items:T[],message:string):T{const v=items[0];assert(v,message);return v}
function optionId(state:GameState,predicate:(id:string)=>boolean){const v=getDecisionView(state);assert(v,'Expected decision view.');const option=v.options.find(o=>predicate(o.id));assert(option,`Expected legal option for ${v.title}.`);return option.id}
function offRunnerKeys(state:GameState){const side=offense(state);const keys=state.pregame[side].battingOrderCardKeys;return [keys[1]??'R1',keys[2]??'R2',keys[3]??'R3']}

export function runNonGbScenarioMatrix(initial:GameState):ScenarioReport {
  const results:ScenarioResult[]=[]
  const test=(id:string,category:string,description:string,fn:TestFn)=>{try{fn();results.push({id,category,description,passed:true,detail:'Expected Rulebook result matched.'})}catch(e){results.push({id,category,description,passed:false,detail:e instanceof Error?e.message:String(e)})}}

  // Universal Rulebook modifier/assertion layer.
  test('MOD-01','Rule modifiers','1B→3B hit advancement receives no ordinary +3 BsR bonus',()=>assert(extraBaseEffectiveBaserunning(14,'1B','3B',0)===14,'Expected BSR 14.'))
  test('MOD-02','Rule modifiers','1B→3B with 2 outs receives only the two-out +3 BsR bonus',()=>assert(extraBaseEffectiveBaserunning(14,'1B','3B',2)===17,'Expected BSR 17.'))
  test('MOD-03','Rule modifiers','2B→HOME hit advancement receives +3 BsR',()=>assert(extraBaseEffectiveBaserunning(14,'2B','HOME',0)===17,'Expected BSR 17.'))
  test('MOD-04','Rule modifiers','2B→HOME with 2 outs receives +6 total BsR',()=>assert(extraBaseEffectiveBaserunning(14,'2B','HOME',2)===20,'Expected BSR 20.'))
  test('MOD-05','Rule modifiers','Tag ups never inherit hit-advancement BsR bonuses',()=>assert(tagUpEffectiveBaserunning(14)===14,'Expected unmodified BSR 14.'))
  test('MOD-06','Rule modifiers','1B→2B tag adds +10 to OF check',()=>assert(tagUpOutfieldBonus('1B','2B')===10,'Expected +10.'))
  test('MOD-07','Rule modifiers','Tag toward home uses RTS 11+',()=>assert(tagUpRtsThreshold([{to:'HOME'}])===11,'Expected 11.'))
  test('MOD-08','Rule modifiers','Tag toward 3B/2B uses RTS 16+',()=>assert(tagUpRtsThreshold([{to:'3B'}])===16,'Expected 16.'))
  test('MOD-09','Natural overrides','Natural 1 is safe even when ordinary total would be an out',()=>assert(fieldingCheckIsOut(1,50,1)===false,'Natural 1 must be safe.'))
  test('MOD-10','Natural overrides','Natural 20 is out even when ordinary total would be safe',()=>assert(fieldingCheckIsOut(20,-50,99)===true,'Natural 20 must be out.'))
  test('MOD-11','Natural overrides','Equality is safe on ordinary fielding comparison',()=>assert(fieldingCheckIsOut(10,14,14)===false,'Equal check must be safe.'))

  // Pre-pitch availability/negative tests.
  test('PRE-01','Manager action eligibility','Intentional walk is available before a pitch',()=>{const s=fixture(initial);assert(getPrePitchActions(s).some(a=>a.id==='INTENTIONAL_WALK'),'Intentional walk missing.')})
  test('PRE-02','Manager action eligibility','Natural steal is unavailable with no runners',()=>{const s=fixture(initial);assert(!getPrePitchActions(s).some(a=>a.id==='NATURAL_STEAL'),'Natural steal should not be offered.')})
  test('PRE-03','Manager action eligibility','Sac bunt is legal with runner on 1B and 2B empty',()=>{const s=fixture(initial);s.bases.first=runner('R1','Runner 1');assert(getPrePitchActions(s).some(a=>a.id==='SAC_BUNT'),'Sac bunt missing.')})
  test('PRE-04','Manager action eligibility','Squeeze is legal with runner on 3B, bases not loaded, INF IN off',()=>{const s=fixture(initial);s.bases.third=runner('R3','Runner 3');assert(getPrePitchActions(s).some(a=>a.id==='SQUEEZE_BUNT'),'Squeeze missing.')})
  test('PRE-05','Manager action eligibility','Squeeze is unavailable after INF IN',()=>{const s=fixture(initial);s.bases.third=runner('R3','Runner 3');s.plateAppearance.infieldIn=true;assert(!getPrePitchActions(s).some(a=>a.id==='SQUEEZE_BUNT'),'Squeeze should be unavailable.')})
  test('PRE-06','Manager action eligibility','INF IN is only offered with runner on 3B and fewer than 2 outs',()=>{const s=fixture(initial);assert(!getPrePitchActions(s).some(a=>a.id==='INFIELD_IN'),'INF IN offered without 3B runner.');s.bases.third=runner('R3','Runner 3');assert(getPrePitchActions(s).some(a=>a.id==='INFIELD_IN'),'INF IN missing with 3B runner.');s.outs=2;assert(!getPrePitchActions(s).some(a=>a.id==='INFIELD_IN'),'INF IN offered with 2 outs.')})
  test('PRE-07','Manager action eligibility','Manager actions are unavailable once Pitch has started',()=>{const s=fixture(initial);s.waitingFor='SWING_ROLL';assert(getPrePitchActions(s).length===0,'Pre-pitch options appeared after Pitch.')})

  // Extra-base selection dependency and RTS.
  test('XB-01','Extra bases','Trailing 1B→3B attempt cannot be selected unless lead 2B→HOME runner also advances',()=>{const s=fixture(initial);const [k1,k2]=offRunnerKeys(s);const lead:RunnerAttempt={runner:runner(k2,'Lead',14),from:'2B',to:'HOME'};const trail:RunnerAttempt={runner:runner(k1,'Trail',14),from:'1B',to:'3B',requiresAttemptId:`${k2}::2B->HOME`};const p=pending(s,'EXTRA_BASE_RUNNER_SELECTION',offense(s),{eligibleAttempts:[lead,trail]});expectThrow(()=>validateDecisionSelection(p,[`${k1}::1B->3B`]),'Trailing runner dependency was not enforced.');validateDecisionSelection(p,[`${k2}::2B->HOME`,`${k1}::1B->3B`])})
  test('XB-02','Extra bases','RTS roll 10 fails',()=>{const s=fixture(initial);const a:RunnerAttempt={runner:runner('R2','Runner',14),from:'2B',to:'HOME'};const p=pending(s,'EXTRA_BASE_RTS',offense(s),{attempts:[a],target:a});const n=resolveDecisionRoll(p,10);assert(!n.pendingDecision,'RTS 10 should end attempt.')})
  test('XB-03','Extra bases','RTS roll 11 passes to OF selection',()=>{const s=fixture(initial);const a:RunnerAttempt={runner:runner('R2','Runner',14),from:'2B',to:'HOME'};const p=pending(s,'EXTRA_BASE_RTS',offense(s),{attempts:[a],target:a});const n=resolveDecisionRoll(p,11);assert(n.pendingDecision?.decisionType==='OUTFIELD_SELECTION','RTS 11 should pass.')})
  test('XB-04','Extra bases','2 outs + throw home skips RTS entirely',()=>{const s=fixture(initial);s.outs=2;const a:RunnerAttempt={runner:runner('R2','Runner',14),from:'2B',to:'HOME'};const p=pending(s,'EXTRA_BASE_DEFENSE_TARGET',defense(s),{attempts:[a]});const id=optionId(p,x=>x.includes('2B->HOME'));const n=confirmManagerDecision(p,[id]);assert(n.pendingDecision?.decisionType==='OUTFIELD_SELECTION','Expected direct OF selection with RTS skipped.')})

  // OF checks including exact modifiers and natural overrides.
  const ofScenario=(roll:number,outs:0|1|2,from:'1B'|'2B',to:'3B'|'HOME',bsr:number)=>{const s=fixture(initial);s.outs=outs;const a:RunnerAttempt={runner:runner('RX','Runner',bsr),from,to};s.bases[from==='1B'?'first':'second']=a.runner;const pos='CF';return resolveDecisionRoll(pending(s,'OUTFIELD_FIELDING_ROLL',defense(s),{attempts:[a],target:a,outfielder:pos,kind:'EXTRA_BASE'}),roll)}
  test('XB-05','Extra bases','Natural 1 OF check is always safe',()=>{const n=ofScenario(1,0,'2B','HOME',1);assert(n.outs===0,'Natural 1 recorded an out.')})
  test('XB-06','Extra bases','Natural 20 OF check is always out',()=>{const n=ofScenario(20,0,'2B','HOME',99);assert(n.outs===1,'Natural 20 did not record out.')})
  test('XB-07','Extra bases','1B→3B ordinary check uses base BsR without +3',()=>assert(extraBaseEffectiveBaserunning(12,'1B','3B',0)===12,'Unexpected modifier.'))
  test('XB-08','Extra bases','Two-out 2B→HOME applies both +3 BsR bonuses',()=>assert(extraBaseEffectiveBaserunning(12,'2B','HOME',2)===18,'Expected +6.'))

  // Tag-up thresholds and +10 defense modifier isolation.
  test('TAG-01','Tag ups','Tag home RTS 10 fails',()=>{const s=fixture(initial);const a:RunnerAttempt={runner:runner('R3','Runner',14),from:'3B',to:'HOME'};const n=resolveDecisionRoll(pending(s,'TAG_UP_RTS',offense(s),{attempts:[a]}),10);assert(!n.pendingDecision,'Tag-home RTS 10 should fail.')})
  test('TAG-02','Tag ups','Tag home RTS 11 passes',()=>{const s=fixture(initial);const a:RunnerAttempt={runner:runner('R3','Runner',14),from:'3B',to:'HOME'};const n=resolveDecisionRoll(pending(s,'TAG_UP_RTS',offense(s),{attempts:[a]}),11);assert(n.pendingDecision?.decisionType==='TAG_UP_DEFENSE_SELECTION','Tag-home RTS 11 should pass.')})
  test('TAG-03','Tag ups','Tag to 3B RTS 15 fails / 16 passes',()=>{const s=fixture(initial);const a:RunnerAttempt={runner:runner('R2','Runner',14),from:'2B',to:'3B'};assert(!resolveDecisionRoll(pending(s,'TAG_UP_RTS',offense(s),{attempts:[a]}),15).pendingDecision,'RTS 15 should fail.');assert(resolveDecisionRoll(pending(s,'TAG_UP_RTS',offense(s),{attempts:[a]}),16).pendingDecision?.decisionType==='TAG_UP_DEFENSE_SELECTION','RTS 16 should pass.')})
  test('TAG-04','Tag ups','Two-out tag still uses unmodified BsR',()=>assert(tagUpEffectiveBaserunning(14)===14,'Two-out bonus leaked into tag up.'))

  // Steals and 1B+.
  test('SB-01','Stolen bases','Natural 1 catcher check is safe',()=>assert(catcherStealCheckIsOut(1,20,1,false)===false,'Natural 1 should be safe.'))
  test('SB-02','Stolen bases','Natural 20 catcher check is out',()=>assert(catcherStealCheckIsOut(20,-20,99,false)===true,'Natural 20 should be out.'))
  test('SB-03','Stolen bases','Catcher-check equality is safe',()=>assert(catcherStealCheckIsOut(10,2,12,false)===false,'Equality should be safe.'))
  test('SB-04','Stolen bases','Steal home adds +15 to catcher check',()=>{assert(catcherStealCheckIsOut(2,0,12,false)===false,'Ordinary steal should be safe.');assert(catcherStealCheckIsOut(2,0,12,true)===true,'Steal-home +15 should make runner out.')})
  test('SB-05','Stolen bases','Natural steal allowance is consumed against non-negative catcher',()=>{const s=fixture(initial);s.bases.first=runner('R1','Runner');const p=beginPrePitchDecision(s,'NATURAL_STEAL');const id=firstOf(getDecisionView(p)?.options??[],'No steal option.').id;const n=confirmManagerDecision(p,[id]);const off=offense(s);assert(n.naturalStolenBaseUsed?.[off]===true,'Natural steal allowance not consumed.')})
  test('1B+-01','1B+','Mandatory 1B+ natural 1 succeeds',()=>{const s=fixture(initial);const r=runner('R1','Runner',10,1);s.bases.first=r;const n=resolveDecisionRoll(pending(s,'ONE_BASE_PLUS_STOLEN_BASE',defense(s),{target:r}),1);assert(n.bases.second?.cardKey===r.cardKey,'Natural 1 did not move runner to 2B.')})
  test('1B+-02','1B+','Mandatory 1B+ natural 20 records out',()=>{const s=fixture(initial);const r=runner('R1','Runner',10,99);s.bases.first=r;const n=resolveDecisionRoll(pending(s,'ONE_BASE_PLUS_STOLEN_BASE',defense(s),{target:r}),20);assert(n.outs===1,'Natural 20 did not record caught stealing.')})

  // Core chart-result behavior and hit/tag/1B+ triggering.
  test('CORE-01','Chart results','K records one out and advances to the next PA',()=>{const s=fixture(initial);const n=resolveCoreResult(s,'K');assert(n.outs===1,'K should record one out.');assert(n.pendingDecision===null,'K should not create a manager decision.')})
  test('CORE-02','Chart results','PU records one out and never offers tag/extra-base advancement',()=>{const s=fixture(initial);s.bases.third=runner('R3','R3');const n=resolveCoreResult(s,'PU');assert(n.outs===1,'PU should record one out.');assert(n.pendingDecision===null,'PU must not offer tag-up.')})
  test('CORE-03','Chart results','FB with runner and fewer than three outs triggers tag-up decision',()=>{const s=fixture(initial);s.bases.third=runner('R3','R3');const n=resolveCoreResult(s,'FB');assert(n.pendingDecision?.decisionType==='TAG_UP_DECISION','FB should create tag-up decision.')})
  test('CORE-04','Chart results','1B with eligible existing runner triggers optional extra-base decision',()=>{const s=fixture(initial);s.bases.first=runner('R1','R1');const n=resolveCoreResult(s,'1B');assert(n.pendingDecision?.decisionType==='EXTRA_BASE_DECISION','1B should create extra-base decision.')})
  test('CORE-05','Chart results','2B with eligible existing runner triggers optional extra-base decision',()=>{const s=fixture(initial);s.bases.first=runner('R1','R1');const n=resolveCoreResult(s,'2B');assert(n.pendingDecision?.decisionType==='EXTRA_BASE_DECISION','2B should create extra-base decision.')})
  test('CORE-06','Chart results','1B+ with 2B empty triggers mandatory non-natural steal',()=>{const s=fixture(initial);const n=resolveCoreResult(s,'1B+');assert(n.pendingDecision?.decisionType==='ONE_BASE_PLUS_STOLEN_BASE','1B+ should create mandatory steal when 2B is open.')})
  test('CORE-07','Chart results','1B+ with 2B occupied after automatic advancement does not trigger mandatory steal',()=>{const s=fixture(initial);s.bases.first=runner('R1','R1');const n=resolveCoreResult(s,'1B+');assert(n.pendingDecision===null,'1B+ should not steal into occupied 2B.')})
  test('CORE-08','Chart results','3B scores all existing runners and leaves batter on 3B',()=>{const s=fixture(initial);s.bases={first:runner('R1','R1'),second:runner('R2','R2'),third:runner('R3','R3')};const n=resolveCoreResult(s,'3B');assert(n.score.away===3,'Triple should score three existing runners.');assert(n.bases.third?.cardKey===s.plateAppearance.batterCardKey,'Batter should occupy 3B.')})
  test('CORE-09','Chart results','HR scores batter plus all existing runners and clears bases',()=>{const s=fixture(initial);s.bases={first:runner('R1','R1'),second:runner('R2','R2'),third:runner('R3','R3')};const n=resolveCoreResult(s,'HR');assert(n.score.away===4,'Grand slam should score four.');assert(!n.bases.first&&!n.bases.second&&!n.bases.third,'HR should clear bases.')})
  test('CORE-10','Chart results','INF IN converts FB to 1B and suppresses tag-up decision',()=>{const s=fixture(initial);s.plateAppearance.infieldIn=true;s.bases.third=runner('R3','R3');const n=resolveCoreResult(s,'FB');assert(n.pendingDecision===null,'INF IN FB conversion must suppress tag.');assert(n.bases.first!==null,'Converted FB should place batter on 1B.')})
  test('CORE-BB-01','Walks','Runner on 2B only holds on BB',()=>{const s=fixture(initial);s.bases.second=runner('R2','R2');const n=resolveCoreResult(s,'BB');assert(n.bases.second?.cardKey==='R2','Runner on 2B must hold.');assert(!n.bases.third,'Runner on 2B must not advance to 3B.')})
  test('CORE-BB-02','Walks','Runner on 1B is forced to 2B on BB',()=>{const s=fixture(initial);s.bases.first=runner('R1','R1');const n=resolveCoreResult(s,'BB');assert(n.bases.second?.cardKey==='R1','Runner on 1B must be forced to 2B.')})
  test('CORE-BB-03','Walks','Runners on 1B/2B are forced to 2B/3B on BB',()=>{const s=fixture(initial);s.bases.first=runner('R1','R1');s.bases.second=runner('R2','R2');const n=resolveCoreResult(s,'BB');assert(n.bases.second?.cardKey==='R1'&&n.bases.third?.cardKey==='R2','Continuous force chain was not applied.')})
  test('CORE-BB-04','Walks','Runners on 2B/3B both hold on BB',()=>{const s=fixture(initial);s.bases.second=runner('R2','R2');s.bases.third=runner('R3','R3');const n=resolveCoreResult(s,'BB');assert(n.bases.second?.cardKey==='R2'&&n.bases.third?.cardKey==='R3','Unforced runners moved on BB.')})

  // Substitution and entry-attribute decision plumbing.
  test('SUB-01','Substitutions','Pinch hitter uses Select → Confirm → attribute mode → resumes same PA',()=>{let s=fixture(initial);const action=getPrePitchActions(s).find(a=>a.id==='PINCH_HITTER');assert(action,'Pinch hitter action unavailable in fixture.');s=beginPrePitchDecision(s,'PINCH_HITTER');const replacement=firstOf(getDecisionView(s)?.options??[],'No pinch hitter replacement.').id;s=confirmManagerDecision(s,[replacement]);assert(s.pendingDecision?.decisionType==='ENTRY_ATTRIBUTE_MODE','Expected entry attribute choice.');s=confirmManagerDecision(s,['DEFAULT_ATTRIBUTES']);assert(s.waitingFor==='PITCH_ROLL','Pinch hitter should resume current PA before pitch.');assert(s.plateAppearance.batterCardKey===replacement,'Replacement should become current hitter.');assert(s.pregame[offense(s)].defaultBatterCardKeys.includes(replacement),'Default hitter mode not stored.')})
  test('SUB-02','Substitutions','Pinch runner replaces runner on the same base without duplicating identity',()=>{let s=fixture(initial);s.bases.first=runner('R1','R1');s=beginPrePitchDecision(s,'PINCH_RUNNER');s=confirmManagerDecision(s,['first']);const replacement=firstOf(getDecisionView(s)?.options??[],'No pinch runner replacement.').id;s=confirmManagerDecision(s,[replacement]);s=confirmManagerDecision(s,['DEFAULT_ATTRIBUTES']);assert(s.bases.first?.cardKey===replacement,'Pinch runner did not replace 1B runner.');const keys=[s.bases.first,s.bases.second,s.bases.third].filter(Boolean).map(r=>r!.cardKey);assert(new Set(keys).size===keys.length,'Pinch runner created duplicate base identity.')})
  test('SUB-03','Substitutions','Defensive substitution reaches entry attribute mode and replaces selected position',()=>{let s=fixture(initial);s=beginPrePitchDecision(s,'DEFENSIVE_SUB');const pos=firstOf(getDecisionView(s)?.options??[],'No defensive positions.').id;s=confirmManagerDecision(s,[pos]);const replacement=firstOf(getDecisionView(s)?.options??[],'No defensive replacement.').id;s=confirmManagerDecision(s,[replacement]);assert(s.pendingDecision?.decisionType==='ENTRY_ATTRIBUTE_MODE','Expected entry attribute mode.');s=confirmManagerDecision(s,['CARD_ATTRIBUTES']);assert(s.pregame[defense(s)].defensiveAlignment[pos as keyof typeof s.pregame.home.defensiveAlignment]===replacement,'Defensive replacement did not inherit position.')})
  test('SUB-04','Substitutions','Pitching change replaces current pitcher before the next pitch',()=>{let s=fixture(initial);s=beginPrePitchDecision(s,'PITCHING_CHANGE');const replacement=firstOf(getDecisionView(s)?.options??[],'No pitching replacement.').id;s=confirmManagerDecision(s,[replacement]);s=confirmManagerDecision(s,['DEFAULT_ATTRIBUTES']);assert(s.pregame[defense(s)].defensiveAlignment.P===replacement,'Pitcher alignment not replaced.');assert(s.plateAppearance.pitcherCardKey===replacement,'Current PA pitcher not replaced.');assert((s.pregame[defense(s)].defaultPitcherCardKeys??[]).includes(replacement),'Default pitcher mode not stored.')})

  test('SB-06','Stolen bases','Negative catcher DEF preserves unlimited natural-steal eligibility even after prior use',()=>{const s=fixture(initial);s.bases.first=runner('R1','Runner');const def=defense(s);const cKey=s.pregame[def].defensiveAlignment.C;assert(cKey,'Catcher missing.');const c=s.pregame[def].roster?.cards[cKey];assert(c,'Catcher card missing.');c.defense.C=-1;s.naturalStolenBaseUsed={...s.naturalStolenBaseUsed,[offense(s)]:true};assert(getPrePitchActions(s).some(a=>a.id==='NATURAL_STEAL'),'Negative catcher should keep natural steals unlimited.')})

  // Bunt tables: every Rulebook boundary.
  for(const [roll,expected] of [[1,'FAILED_PITCHER_CHART'],[2,'FAILED_PITCHER_CHART'],[3,'STRIKEOUT'],[4,'STRIKEOUT'],[5,'LEAD_RUNNER_OUT'],[6,'SUCCESS'],[20,'SUCCESS']] as const){test(`BUNT-NW-${roll}`,'Sac bunt',`No-wheel sac bunt boundary roll ${roll} = ${expected}`,()=>{assert(noWheelSacBuntOutcome(roll)===expected,`Expected ${expected}.`);const s=fixture(initial);s.bases.first=runner('R1','Runner');const n=resolveDecisionRoll(pending(s,'SAC_BUNT_RTS',offense(s),{}),roll);if(expected==='FAILED_PITCHER_CHART')assert(n.waitingFor==='SWING_ROLL'&&n.plateAppearance.advantage==='pitcher','Failed bunt must resume on pitcher chart.');else if(expected==='STRIKEOUT')assert(n.outs===1,'Roll 3-4 must record a strikeout/out.');else if(expected==='LEAD_RUNNER_OUT'){assert(n.outs===1,'Roll 5 must record one out.');assert(n.bases.first!==null,'Batter must reach 1B when lead runner is out.')}else{assert(n.outs===1,'Successful sacrifice bunt must record the batter out.');assert(n.bases.second?.cardKey==='R1','Successful bunt must advance the lead runner.');assert(n.bases.first===null,'Successful sacrifice bunt should leave 1B open after the batter is retired.')}})}
  test('BUNT-W-15','Sac bunt','Wheel play roll 15 = all forced runners advance, hitter safe, no out',()=>{const s=fixture(initial);s.bases.first=runner('R1','Runner');const n=resolveDecisionRoll(pending(s,'SAC_BUNT_WHEEL_RTS',offense(s),{}),15);assert(n.outs===0,'Wheel 15 should record no out.');assert(n.bases.first!==null,'Hitter should be safe.')})
  test('BUNT-W-16','Sac bunt','Wheel play roll 16 = lead runner out, hitter safe',()=>{const s=fixture(initial);s.bases.first=runner('R1','Runner');const n=resolveDecisionRoll(pending(s,'SAC_BUNT_WHEEL_RTS',offense(s),{}),16);assert(n.outs===1,'Wheel 16 should record one out.');assert(n.bases.first!==null,'Hitter should be safe.')})

  // Squeeze boundaries.
  for(const [roll,outDelta,runDelta] of [[1,1,0],[7,1,0],[8,1,0],[15,1,0],[16,1,1],[19,1,1],[20,0,1]] as const){test(`SQ-${roll}`,'Squeeze bunt',`Squeeze boundary roll ${roll}`,()=>{const s=fixture(initial);s.bases.third=runner('R3','Runner');const n=resolveDecisionRoll(pending(s,'SQUEEZE_BUNT_ROLL',offense(s),{}),roll);assert(n.outs===outDelta,`Expected ${outDelta} out(s), got ${n.outs}.`);assert(n.score.away===runDelta,`Expected ${runDelta} run(s), got ${n.score.away}.`)})}

  // Intentional walk forcing and INF IN confirmation.
  test('IBB-01','Intentional walk','Bases loaded intentional walk forces exactly one run',()=>{const s=fixture(initial);s.bases={first:runner('R1','R1'),second:runner('R2','R2'),third:runner('R3','R3')};const p=beginPrePitchDecision(s,'INTENTIONAL_WALK');const n=confirmManagerDecision(p,['CONFIRM_INTENTIONAL_WALK']);assert(n.score.away===1,'Loaded IBB should force one run.');assert(n.bases.first&&n.bases.second&&n.bases.third,'Bases should remain loaded with batter replacing forced chain.')})
  test('INF-01','Infield in','Confirming INF IN persists for current PA and resumes Pitch',()=>{const s=fixture(initial);s.bases.third=runner('R3','R3');const p=beginPrePitchDecision(s,'INFIELD_IN');const n=confirmManagerDecision(p,['CONFIRM_INFIELD_IN']);assert(n.plateAppearance.infieldIn===true,'INF IN flag missing.');assert(n.waitingFor==='PITCH_ROLL','Expected Pitch Roll after confirmation.')})

  // OF rotation contract.
  test('OF-01','Outfield rotation','Selected outfielder is unavailable until other eligible OF have caught up in usage',()=>{const s=fixture(initial);const a:RunnerAttempt={runner:runner('R2','Runner'),from:'2B',to:'HOME'};let p=pending(s,'OUTFIELD_SELECTION',defense(s),{attempts:[a],target:a,kind:'EXTRA_BASE'});const view=getDecisionView(p);assert(view&&view.options.length>=2,'Need at least two OF assignments for rotation test.');const selected=view.options[0].id;p=confirmManagerDecision(p,[selected]);const usedPos=selected.replace('OF::','');const later=pending({...p,pendingDecision:null,status:'in_progress'},'OUTFIELD_SELECTION',defense(s),{attempts:[a],target:a,kind:'EXTRA_BASE'});const ids=getDecisionView(later)?.options.map(o=>o.id)??[];assert(!ids.includes(`OF::${usedPos}`),'Used OF was immediately eligible again.')})


  test('TAG-05','Tag ups','1B→2B tag-up is unavailable at +7 and available at +8',()=>{let s=fixture(initial);s.bases.first=runner('R1','Runner');s.score={away:7,home:0};let n=resolveCoreResult(s,'FB');assert(n.pendingDecision?.decisionType==='TAG_UP_DECISION','Expected tag decision at +7.');n=confirmManagerDecision(n,['ATTEMPT_TAG_UP']);const ids7=getDecisionView(n)?.options.map(o=>o.id)??[];assert(!ids7.some(id=>id.includes('1B->2B')),'1B→2B tag should be unavailable at +7.');s=fixture(initial);s.bases.first=runner('R1','Runner');s.score={away:8,home:0};n=resolveCoreResult(s,'FB');n=confirmManagerDecision(n,['ATTEMPT_TAG_UP']);const ids8=getDecisionView(n)?.options.map(o=>o.id)??[];assert(ids8.some(id=>id.includes('1B->2B')),'1B→2B tag should be available at +8.')})

  test('SUB-05','Substitutions','Double switch supports active fielder moving to P plus one bench replacement',()=>{let s=fixture(initial);const def=defense(s);const action=getPrePitchActions(s).find(a=>a.id==='DOUBLE_SWITCH');assert(action,'Double switch unavailable in fixture.');s=beginPrePitchDecision(s,'DOUBLE_SWITCH');const pitchView=getDecisionView(s);const active=pitchView?.options.find(o=>o.id.startsWith('ACTIVE::'));assert(active,'No active fielder→P option.');const [,vacated,newPitcher]=active.id.split('::');const oldPitcher=s.pregame[def].defensiveAlignment.P;s=confirmManagerDecision(s,[active.id]);assert(s.pendingDecision?.decisionType==='DOUBLE_SWITCH_FIELDER','Expected new-fielder selection.');const newFielder=firstOf(getDecisionView(s)?.options??[],'No bench fielder for active-player double switch.').id;s=confirmManagerDecision(s,[newFielder]);assert(s.pendingDecision?.decisionType==='ENTRY_ATTRIBUTE_MODE','Expected final attribute confirmation.');const beforeOrder=[...s.pregame[def].battingOrderCardKeys];s=confirmManagerDecision(s,['CARD_ATTRIBUTES']);assert(s.pregame[def].defensiveAlignment.P===newPitcher,'Active fielder did not move to P.');assert(s.pregame[def].defensiveAlignment[vacated as keyof typeof s.pregame.home.defensiveAlignment]===newFielder,'Bench player did not fill vacated field position.');assert(!s.pregame[def].battingOrderCardKeys.includes(oldPitcher??''),'Outgoing pitcher remained in batting order.');assert(s.pregame[def].battingOrderCardKeys.includes(newPitcher),'Existing player disappeared from batting order.');assert(s.pregame[def].battingOrderCardKeys.includes(newFielder),'New fielder did not enter batting order.');assert(beforeOrder.includes(newPitcher),'Fixture active pitcher candidate was not already in batting order.')})

  test('FAT-ID-01','State integrity','Identical pitcher card keys on opposite teams keep independent fatigue state',()=>{const s=fixture(initial);const home='home' as const,away='away' as const;const sourceKey=s.pregame[home].defensiveAlignment.P;assert(sourceKey,'Home pitcher missing.');const source=s.pregame[home].roster?.cards[sourceKey];assert(source,'Home pitcher card missing.');assert(s.pregame[away].roster,'Away roster missing.');s.pregame[away].roster!.cards[sourceKey]=structuredClone(source);s.pregame[away].defensiveAlignment.P=sourceKey;s.pregame[away].startingPitcherCardKey=sourceKey;s.pregame[away].battingOrderCardKeys[8]=sourceKey;s.pitcherEntryDefenseOuts={...(s.pitcherEntryDefenseOuts??{}),[pitcherInstanceKey(home,sourceKey)]:0,[pitcherInstanceKey(away,sourceKey)]:0};s.pitcherRunsAllowed={...(s.pitcherRunsAllowed??{}),[pitcherInstanceKey(home,sourceKey)]:9,[pitcherInstanceKey(away,sourceKey)]:0};s.half='top';s.plateAppearance.pitcherCardKey=sourceKey;const homeControl=effectiveCurrentPitcherControl(s);s.half='bottom';s.plateAppearance.pitcherCardKey=sourceKey;const awayControl=effectiveCurrentPitcherControl(s);assert(homeControl!==awayControl,'Opposing copies of same pitcher card shared fatigue state.');assert(awayControl>(homeControl),'Fresh opposing copy should retain higher Control.')})

  // Universal state integrity for every scenario is also enforced by result-specific checks;
  // this explicit fixture test protects the runner uniqueness contract.
  test('STATE-01','State integrity','Scenario fixture starts with legal outs/cursors and unique bases',()=>{const s=fixture(initial);assert(s.outs>=0&&s.outs<=3,'Invalid outs.');assert(s.lineupCursor.home>=0&&s.lineupCursor.home<=8,'Invalid home cursor.');assert(s.lineupCursor.away>=0&&s.lineupCursor.away<=8,'Invalid away cursor.')})

  const categories:ScenarioReport['categories']={}
  for(const r of results){const c=categories[r.category]??{total:0,passed:0};c.total++;if(r.passed)c.passed++;categories[r.category]=c}
  return {total:results.length,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,categories,results}
}
