export const RULE_SECTIONS = [
  {
    "id": "section-1",
    "number": 1,
    "title": "Introduction",
    "lines": [
      {
        "depth": 1,
        "text": "Elements Baseball is a baseball card based, board game simulator for Major League Baseball games."
      },
      {
        "depth": 1,
        "text": "The game includes both elements of managing on field players as well as elements of front office roster management with corresponding transactions."
      },
      {
        "depth": 1,
        "text": "Players have the option to build fully customizable rosters of various players & seasons throughout all of Major League Baseball history, as well as recreating past historical games, series, &/or seasons using entire team vs team, year vs year, & season vs season matchups."
      },
      {
        "depth": 1,
        "text": "On field outcomes are generated by two opposing players rolling a 20-sided die for all results."
      }
    ]
  },
  {
    "id": "section-2",
    "number": 2,
    "title": "Roster Construction for General Gameplay",
    "lines": [
      {
        "depth": 1,
        "text": "Two players each compile their own custom rosters prior to the start of each game."
      },
      {
        "depth": 2,
        "text": "Both players should agree on an overall roster size, the number of hitters & pitchers on each roster, the available cards to select from, & an overall points cap prior to playing each game."
      },
      {
        "depth": 2,
        "text": "Elements Baseball recommends a 26-man overall roster size with a 6,000 point maximum, with each team consisting of 13 pitchers & 13 hitters, including at least 1 hitter that qualifies at: C, 1B, 2B, 3B, SS, LF, CF, and RF, along with 1 additional hitter to play at DH."
      },
      {
        "depth": 3,
        "text": "Please note that all players are always eligible to play DH."
      },
      {
        "depth": 1,
        "text": "Before the start of each game, both players must agree on who will be the home & away teams."
      },
      {
        "depth": 2,
        "text": "Elements Baseball recommends assigning home & away teams via a die roll as outlined below."
      },
      {
        "depth": 3,
        "text": "Each player completes one die roll, with the player who rolls highest being assigned the home team & the player who rolls the lowest being assigned the away team."
      },
      {
        "depth": 4,
        "text": "If both die rolls are the same number, re-roll the attempts until there is no tie."
      },
      {
        "depth": 1,
        "text": "To start each game, the home team announces their starting pitcher & away team their first hitter."
      },
      {
        "depth": 2,
        "text": "Once both players are announced, the defensive team completes a die roll & adds the number rolled to the Control of the pitcher in order to determine the total “pitch” number."
      },
      {
        "depth": 3,
        "text": "The pitch number then determines which chart the “swing” is rolled on."
      },
      {
        "depth": 4,
        "text": "If the pitch number is greater than the hitter’s On Base, the roll for the swing is completed on the pitcher’s chart."
      },
      {
        "depth": 4,
        "text": "If the pitch number is less than the hitter’s On Base, the roll for the swing is completed on the hitter’s chart."
      },
      {
        "depth": 4,
        "text": "If the pitch number is equal to the hitter’s On Base, the roll for the swing is determined by whichever player has the platoon advantage as outlined below."
      },
      {
        "depth": 4,
        "text": "If the pitcher & hitter are both right-handed, or the pitcher & hitter are both left-handed, the swing is on the pitcher’s chart."
      },
      {
        "depth": 4,
        "text": "If the pitcher is right-handed & the hitter is left-handed, or the pitcher is left-handed & the hitter is right-handed, the swing is on the hitter’s chart."
      },
      {
        "depth": 4,
        "text": "If the hitter is a switch hitter, the swing is automatically on the hitter’s chart."
      },
      {
        "depth": 4,
        "text": "If the pitcher is a switch pitcher & the hitter is left-handed only or right-handed only, the swing is automatically on the pitcher’s chart."
      },
      {
        "depth": 2,
        "text": "Once the “pitch” number has been rolled & the swing chart selected, the offensive team then completes a die roll to determine the “swing” result as determined by the previously selected swing chart."
      },
      {
        "depth": 3,
        "text": "For all at bats, the die rolls for both the “pitch” & “swing” must always be completed."
      },
      {
        "depth": 3,
        "text": "Any die rolls completed prior to the offense team formally announcing their current hitter as at bat are void & are to be re-rolled after the hitter is formally announced."
      },
      {
        "depth": 2,
        "text": "This process of determining the “pitch” & “swing” is then repeated for every at bat throughout a game until the game has been completed."
      },
      {
        "depth": 1,
        "text": "For any additional gameplay questions, please reference Section VII Advanced Gameplay & In-Game Components of this rulebook."
      },
      {
        "depth": 2,
        "text": "For any rule clarifications that are not included within Section VIII Advanced Gameplay & In-Game Components, players are to defer to the current Major League Baseball rulebook."
      }
    ]
  },
  {
    "id": "section-3",
    "number": 3,
    "title": "The Cards",
    "lines": [
      {
        "depth": 1,
        "text": "This is an image of a typical hitter’s card:"
      },
      {
        "depth": 2,
        "text": ""
      },
      {
        "depth": 3,
        "text": "The On Base score is in the upper right corner in red with the player points & fielding scores for all card eligible positions directly underneath."
      },
      {
        "depth": 3,
        "text": "BsR & SB scores are both under the word “On Base”."
      },
      {
        "depth": 3,
        "text": "The hitter’s fatigue score is directly to the left of the player points with their hitting handedness directly underneath."
      },
      {
        "depth": 3,
        "text": "The swing chart is listed in the lower right corner with the card year underneath."
      },
      {
        "depth": 3,
        "text": "The card number, rarity, & any accolade icons are listed in the lower left corner."
      },
      {
        "depth": 3,
        "text": "All 1B+ results are the same as standard 1B results with the exception that the hitter must also make a mandatory stolen base attempt of 2B if the base is unoccupied."
      },
      {
        "depth": 0,
        "text": "This is an image of a typical pitcher’s card:"
      },
      {
        "depth": 1,
        "text": ""
      },
      {
        "depth": 2,
        "text": "The Control score is in the upper right corner in red with the player points directly underneath."
      },
      {
        "depth": 2,
        "text": "Fatigue score & IP length are both under the word “Control”."
      },
      {
        "depth": 2,
        "text": "The pitcher’s handedness is directly to the left of the player’s points."
      },
      {
        "depth": 2,
        "text": "The swing chart is listed in the lower right corner with the card year underneath."
      },
      {
        "depth": 2,
        "text": "The card number, rarity, & any accolade icons are listed in the lower left corner."
      },
      {
        "depth": 2,
        "text": "All PU results are the same as standard FB results with the exception that all runners cannot make any extra base attempts as this is an infield “Pop Up” result."
      },
      {
        "depth": 0,
        "text": "These are images of standard 2-way player cards:"
      },
      {
        "depth": 1,
        "text": ""
      },
      {
        "depth": 2,
        "text": "For hitter dominant cards, On Base score, player points, fielding, BsR, SB, & fatigue scores, hitter handedness, the hitter swing chart, year, card number, rarity, & accolade icons are all in the same locations as on a typical hitter’s card."
      },
      {
        "depth": 3,
        "text": "Additionally the pitcher Control score is located in the upper left corner with the pitcher swing chart directly underneath."
      },
      {
        "depth": 3,
        "text": "IP length & pitcher fatigue score are both under the word “Control” with pitcher handedness directly to the right of the pitcher swing chart."
      },
      {
        "depth": 2,
        "text": "For pitcher dominant cards, Control score, player points, fatigue score, IP length, pitcher handedness, the pitcher swing chart, year, card number, rarity, & accolade icons are all in the same locations as on a typical pitcher’s card."
      },
      {
        "depth": 3,
        "text": "Additionally the hitter On Base score is located in the upper left corner with the hitter swing chart directly underneath."
      },
      {
        "depth": 3,
        "text": "BsR & SB scores are both under the words “On Base” with hitter fatigue score & hitter handedness directly to the right of the hitter swing chart."
      },
      {
        "depth": 3,
        "text": "If eligible, any defensive fielding scores will appear directly underneath the hitter swing chart."
      },
      {
        "depth": 0,
        "text": "This is an image of an atypical player card:"
      },
      {
        "depth": 1,
        "text": ""
      },
      {
        "depth": 2,
        "text": "The Control score is in the upper right corner in red with the player points directly underneath."
      },
      {
        "depth": 2,
        "text": "Fatigue score & IP length are both under the word “Control”."
      },
      {
        "depth": 2,
        "text": "The pitcher’s handedness is directly to the left of the player’s points."
      },
      {
        "depth": 2,
        "text": "The swing chart is listed in the lower right corner with the card year underneath."
      },
      {
        "depth": 2,
        "text": "The card number, rarity, & any accolade icons are listed in the lower left corner."
      },
      {
        "depth": 2,
        "text": "Atypical player attributes will also be listed directly underneath player points."
      },
      {
        "depth": 3,
        "text": "For example, this player card has both BsR & SB scores as well as 1B, 3B, SS, & LF fielding scores listed directly underneath player points."
      },
      {
        "depth": 2,
        "text": "Atypical cards will vary with what & how many atypical player attributes are listed."
      }
    ]
  },
  {
    "id": "section-4",
    "number": 4,
    "title": "Modern League Roster Construction & Pre-Game Checks for Online League Gameplay",
    "lines": [
      {
        "depth": 1,
        "text": "Each GM compiles their own custom 26-man roster."
      },
      {
        "depth": 2,
        "text": "Rosters must be posted in their entirety on each specific GM’s Elements League Workbook roster tab, with all 26 rosters slots being accounted for."
      },
      {
        "depth": 2,
        "text": "Rosters that are not posted on a specific GM’s roster tab are not considered official & are not eligible to be used for league gameplay."
      },
      {
        "depth": 3,
        "text": "Any league games played with ineligible rosters are considered void & are considered to have never been played for either team."
      },
      {
        "depth": 3,
        "text": "It is the responsibility of both GMs to ensure prior to the start of a game that neither their own roster nor their opponent’s roster are ineligible for league gameplay."
      },
      {
        "depth": 1,
        "text": "Every 26-man roster must both never exceed the 6,000 points cap & must always contain at least 13 players with an On Base score & 13 players with a Control score."
      },
      {
        "depth": 2,
        "text": "For non-modern league seasons & tournaments, the roster size, points cap, &/or other team building attributes will be adjusted to more accurately represent the desired era of gameplay."
      },
      {
        "depth": 3,
        "text": "Any non-modern league rule adjustments will be explicitly announced in the league Discord by the league commissioner."
      },
      {
        "depth": 3,
        "text": "For era & year locked non-modern seasons, all games are to use the earliest locked year of the MLB rulebook for all MLB rules."
      },
      {
        "depth": 1,
        "text": "Prior to the start of each game, both GMs must individually post their full starting line-ups & starting pitcher in whichever #the-fields Discord channel the game is taking place."
      },
      {
        "depth": 2,
        "text": "Once both starting line-ups & starting pitchers have been posted, both GMs must roll a die in order to determine the home & away teams."
      },
      {
        "depth": 3,
        "text": "After each GM completes a die roll, the GM with the higher die roll is assigned the home team & the GM with the lower die roll is assigned the away team."
      },
      {
        "depth": 4,
        "text": "If both die rolls are the same number, re-roll the attempts until there is no tie."
      },
      {
        "depth": 1,
        "text": "Any additional modern league roster construction & pre-game checks along with any rules &/or penalties can be assigned by the league commissioner on an ad-hoc basis as necessary."
      }
    ]
  },
  {
    "id": "section-5",
    "number": 5,
    "title": "Online Game Etiquette & Reporting",
    "lines": [
      {
        "depth": 1,
        "text": "After all roster construction & pre-game checks have been completed, the home team announces their starting pitcher has taken the mound & the away team announces their lead-off hitter has stepped up to the plate, the game can officially begin with the defense rolling for the first “pitch”."
      },
      {
        "depth": 2,
        "text": "Throughout the game, each offensive GM must always announce their current hitter prior to any die rolls taking place for that at bat."
      },
      {
        "depth": 3,
        "text": "Hitters are announced by either the offensive GM sending an image of the hitter’s card or by messaging the hitter’s name, year, & current On Base score."
      },
      {
        "depth": 4,
        "text": "When announcing a hitter or pitcher that has active fatigue effects their On Base or Control score, the GM must also announce the player’s current On Base or Control score."
      },
      {
        "depth": 1,
        "text": "After the completion of each game, the winning GM submits the following information in the #results channel in Discord."
      },
      {
        "depth": 2,
        "text": "The names of both GMs, the final score, any offensive players who have a plate appearance & a fatigue score of 10 or above, all pitchers & their card year used in the game for each team, all pitchers who pitched beyond their card IP, all pitchers who enter a game with a positive Control score but end their appearance having pitched with a negative Control score, & any players who entered a game with active fatigue effects."
      },
      {
        "depth": 3,
        "text": "The following key can be used to denote pitcher usage information:"
      },
      {
        "depth": 4,
        "text": "Use a + sign for pitchers who pitch beyond their card IP score."
      },
      {
        "depth": 4,
        "text": "Use a % sign for pitchers who enter a game with a positive Control score but end their appearance having pitched with a negative Control score."
      },
      {
        "depth": 4,
        "text": "Use ^n for players who entered a game with active fatigue effects with “n” being the total number of games remaining to rest fully rested & no fatigue."
      },
      {
        "depth": 3,
        "text": "If all of the above information is not posted fully, the game is considered incomplete."
      },
      {
        "depth": 4,
        "text": "Any incomplete game, partially completed game, or game played with an ineligible rosters is considered void with no stats accrued for either team."
      },
      {
        "depth": 1,
        "text": "Games must always be at least 9 innings in length in order to be considered completed."
      },
      {
        "depth": 2,
        "text": "Abandoning games, i.e. rage quitting, or manipulating game outcomes solely to accrue a game played while not actively competing to win, i.e. bunting out full innings of games, is highly discouraged & can be penalized by the league commissioner as he sees fit."
      },
      {
        "depth": 1,
        "text": "Participate & play your games as if someone you care about is watching & reading your messages."
      },
      {
        "depth": 2,
        "text": "This should go without saying, but act as though all of your messages & interactions with others are seen by your loved ones & just generally act compassionately & of sound mind."
      },
      {
        "depth": 2,
        "text": "The commissioner reserves the right to penalize GMs who do not follow this rule."
      }
    ]
  },
  {
    "id": "section-6",
    "number": 6,
    "title": "Online League Structure",
    "lines": [
      {
        "depth": 1,
        "text": "The online league is structured for both communal gameplay & ad-hoc participation."
      },
      {
        "depth": 2,
        "text": "This league structure ensures GMs are never required to play any regular season games & may opt in or out for any length of time, in order to focus their time on what they see fit."
      },
      {
        "depth": 3,
        "text": "During the playoffs, GMs are requested to provide a general time frame & available dates to their playoff opponents in order to schedule & complete playoff games."
      },
      {
        "depth": 4,
        "text": "GMs who are unable to provide &/or play playoff games in a timely manner are subject to forfeiture of playoff games &/or series at the discretion of the league commissioner."
      },
      {
        "depth": 1,
        "text": "The league is structured similarly to Major League Baseball with both a regular season & playoffs."
      },
      {
        "depth": 2,
        "text": "The regular season is an open-play format where any GM can play any other GM at any time so long as neither GM has another currently active or incomplete ongoing game."
      },
      {
        "depth": 2,
        "text": "The goal of the regular season is for GMs to play as many games as they would like while also experimenting with various forms of team building philosophies & roster management styles."
      },
      {
        "depth": 2,
        "text": "Total regular season games played are used to determine both overall seeding & qualifying eligibility for an upcoming playoff."
      },
      {
        "depth": 3,
        "text": "Playoff qualification varies each season but is typically achieved by playing at least 1 game per week for the full length of the regular season."
      },
      {
        "depth": 2,
        "text": "Rosters are fluid throughout the regular season with each GM being able to edit their roster to include any in-season eligible players within their existing collection at any time, so long as the GM does not have any active or incomplete ongoing games."
      },
      {
        "depth": 3,
        "text": "After each GM completes 9 regular season games, all players on both the active & inactive rosters receive 1 additional rest day applied to their fatigue scores."
      },
      {
        "depth": 3,
        "text": "After each GM completes 81 regular season games, all players on both the active & inactive rosters receive 5 additional rest days applied to their fatigue scores."
      },
      {
        "depth": 1,
        "text": "After the conclusion of the regular season, the league completes a playoff."
      },
      {
        "depth": 2,
        "text": "Each playoff will have a unique structure based on how many eligible GMs are participating."
      },
      {
        "depth": 3,
        "text": "The playoff structure for each playoff year will be announced by the league commissioner prior to the start of any playoff games."
      },
      {
        "depth": 2,
        "text": "During the playoffs, GMs will be assigned an opponent & play a set amount of games in order to determine a playoff series winner, all culminating in one GM winning the overall playoffs for that specific season."
      },
      {
        "depth": 2,
        "text": "Rosters are locked during the playoffs with all GMs submitting their playoff rosters via their league workbook team tab prior to the start of any playoff games."
      },
      {
        "depth": 2,
        "text": "Playoffs formats vary for each playoffs with the typical format consisting of all in-season eligible players within a GM’s existing collection being eligible to be rostered except the following:"
      },
      {
        "depth": 3,
        "text": "Player cards with fatigue scores of 10+ who accrue 0 plate appearances &/or 0.0 IP in the regular season for a given GM are ineligible to be included on playoff rosters."
      },
      {
        "depth": 4,
        "text": "2-way players who only appear at one position on their card in the regular season are only eligible to make a play at that position in the playoffs."
      },
      {
        "depth": 4,
        "text": "For example: A card with a hitter fatigue score of 0 who also has a pitcher fatigue score of 161 who has appeared in 0 regular season games for a given GM is eligible to make a player appearance as a hitter but not as a pitcher in the playoffs."
      },
      {
        "depth": 1,
        "text": "All GMs also unlock various player cards for their individual personal collections via achievement milestones throughout both the regular season & playoffs."
      },
      {
        "depth": 2,
        "text": "All milestones are unique to each individual regular season &/or playoffs with new milestones being announced at the conclusion of each regular season &/or playoffs."
      },
      {
        "depth": 2,
        "text": "Each season’s milestones are posted in the Milestones tab within the league workbook."
      },
      {
        "depth": 3,
        "text": "Additional hidden Milestones exist within each regular season & are revealed once one GM reaches certain hidden criteria."
      }
    ]
  },
  {
    "id": "section-7",
    "number": 7,
    "title": "Advanced In-Game Components",
    "lines": [
      {
        "depth": 1,
        "text": "Fielding Scores & Checks"
      },
      {
        "depth": 2,
        "text": "Fielding scores are used by GMs to complete three types of “fielding checks” throughout a game as outlined below."
      },
      {
        "depth": 3,
        "text": "Catcher fielding check = Add the C fielding score + a die roll."
      },
      {
        "depth": 3,
        "text": "Infield fielding check = Add a variable combination of your 1B, 2B, 3B, and SS fielding scores + a die roll."
      },
      {
        "depth": 3,
        "text": "Outfield fielding check = Select 1 of your LF, CF, or RF fielding scores + a die roll."
      },
      {
        "depth": 2,
        "text": "Infield fielding check scores can also change results on a pitcher’s chart during a game whenever the combined total infield fielding check score is negative for any given pitch."
      },
      {
        "depth": 3,
        "text": "For every negative number the combined total infield fielding score is away from 0, change the corresponding amount of GB results on the pitcher’s chart to 1B results starting at the highest GB number."
      },
      {
        "depth": 4,
        "text": "For example: If the combined total infield fielding score is currently -3 for the 1B, 2B, 3B, and SS, & the pitcher in the game has a 6-12 GB range, then change all 10, 11 & 12 rolled results from a GB to a 1B."
      },
      {
        "depth": 3,
        "text": "If the total number of GB results on a pitcher’s chart is less than the combined total infield fielding score is away from 0, change all of the GB results as well as any K, then PU, then FB results in that order to 1B results starting at the highest GB number."
      },
      {
        "depth": 4,
        "text": "For example: If the combined total infield fielding score is currently -3 for the 1B, 2B, 3B, and SS, & the pitcher in the game has a 2-10 K & 11-12 GB range, then change all 10, 11 & 12 rolled results from a GB to a 1B."
      },
      {
        "depth": 0,
        "text": "Managerial Defensive Decisions"
      },
      {
        "depth": 1,
        "text": "Both GMs must assign all players in their starting line-ups to a defensive position prior to the start of each game & for all subsequent pitches throughout an entire game."
      },
      {
        "depth": 2,
        "text": "The defensive positions are: P, C, 1B, 2B, 3B, SS, LF, CF, RF & when applicable, DH."
      },
      {
        "depth": 2,
        "text": "Players in the starting line-ups may only start a game at a position where they have an on-card fielding score, with the exception of DH where all players are eligible."
      },
      {
        "depth": 2,
        "text": "A player may only start a game at P if they have a Control score on their card & their pitcher charts are in the primary position on their player card."
      },
      {
        "depth": 3,
        "text": "All players are eligible to play out of position defensively at positions where they do not have an on-card fielding score once the first plate appearance of the game is complete."
      },
      {
        "depth": 4,
        "text": "Players without an on-card fielding score default to a fielding score of -10 for all positions where they do not have an on-card fielding score."
      },
      {
        "depth": 1,
        "text": "When there is a runner on 1B with less than 2 outs & the swing is a GB result, the defensive GM must opt to either take a singular automatic out or a standard GB double play attempt."
      },
      {
        "depth": 2,
        "text": "If the defensive GM opts to take the singular automatic out, the defensive GM then also completes a “Roll-To-See” or RTS to determine which runner will be out."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 1-5: The runner heading to 1B is out, the runner heading to 2B is safe, & any other runners are safe, advancing 1 base."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 6-20: The runner heading to 1B is safe, the runner heading to 2B is out, & any other runners are safe, advancing 1 base."
      },
      {
        "depth": 2,
        "text": "If the defensive GM opts to attempt a standard GB double play, the defensive GM then completes the following steps in order."
      },
      {
        "depth": 3,
        "text": "The defensive GM completes the first of 2 infield fielding checks by combining 2 of the 3 fielding scores of the 2B, 3B, & SS with the fielding score of the 1B + a die roll, against the BsR of the runner heading to 2B."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, all runners are safe on a fielder’s choice where no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runner heading to 2B & the runner heading to 1B are both out on an automatic standard GB double play & any other runners are safe, advancing 1 base, or 3 outs have been recorded & the inning is complete."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is greater than the BsR of the runner heading to 2B, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is less than or equal to the BsR of the runner heading to 2B, the runner is safe."
      },
      {
        "depth": 3,
        "text": "Once the first infield fielding check is complete, the defensive GM then completes the second infield fielding check by combining the same 2 of the 3 fielding scores of the 2B, 3B, & SS with the fielding score of the 1B + a die roll, now against the BsR of the runner heading to 1B."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, the runner heading to 1B is automatically safe, the runner heading to 2B still has the same result as determined in the previous roll, & all other runners are safe on a fielder’s choice where no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runner heading to 1B is automatically out, the runner heading to 2B still has the same result as determined in the previous roll, & all other runners are either safe on either a fielder’s choice or 3 outs have been recorded & the inning is complete."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is greater than the BsR of the runner heading to 1B, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is less than or equal to the BsR of the runner heading to 1B, the runner is safe."
      },
      {
        "depth": 1,
        "text": "The defensive GM must also track which infielder combinations were used during each double play attempt with no duplicate combination being used 2 times until all combinations have been used 1 time."
      },
      {
        "depth": 2,
        "text": "For example: If the defensive GM combines the 2B & SS with the 1B for the first double play attempt of the game, this exact combination cannot be used again until all other combinations have been used 1 time."
      },
      {
        "depth": 3,
        "text": "Once all 3 of the infield fielding check combinations have been used for double play attempts 1 time, this counter resets & the process of using all combinations 2 times begins, continually repeating until the game is complete."
      },
      {
        "depth": 1,
        "text": "When there are runners on 1B & 2B with less than 2 outs, the swing is a GB result, & an infield fielding check combination including the 3B is available to be used, the defensive GM must opt to either take a singular automatic out, a standard GB double play attempt, or 3B-to-1B double play attempt."
      },
      {
        "depth": 2,
        "text": "If the defensive GM opts to take the singular automatic out, the defensive GM then also completes a “Roll-To-See” or RTS to determine which runner will be out."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 1-5: The runner heading to 1B is out, the runners heading to 2B & 3B are safe, & any other runner is also safe, advancing 1 base."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 6-15: The runner heading to 1B is safe, the runner heading to 2B is out, the runner heading to 3B is safe, & any other runner is safe, advancing 1 base."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 16-20: The runners heading to 1B & 2B are safe, the runner heading to 3B is out, & any other runner is safe, advancing 1 base."
      },
      {
        "depth": 2,
        "text": "If the defensive GM opts to attempt a standard GB double play attempt, follow the guidelines in Step 3 above."
      },
      {
        "depth": 2,
        "text": "If the defensive GM opts to attempt a 3B-to-1B double play, the defensive GM then completes the following steps in order."
      },
      {
        "depth": 3,
        "text": "The defensive GM completes the first of 2 infield fielding checks by combining the fielding score of the 3B & 1B with either the 2B or SS + a die roll, against the BsR of the runner heading to 3B."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, all runners are safe on a fielder’s choice where no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runner heading to 3B & the runner heading to 1B are both out on an automatic 3B-to-1B double play & any other runners are safe advancing 1 base or 3 outs have been recorded & the inning is complete."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is greater than the BsR of the runner heading to 3B, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is less than or equal to the BsR of the runner heading to 3B, the runner is safe."
      },
      {
        "depth": 3,
        "text": "Once the first infield fielding check is complete, the defensive GM then completes the second infield fielding check by combining the same fielding score of the 3B & 1B with the same 2B or SS + a die roll, now against the BsR of the runner heading to 1B."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, the runner heading to 1B is automatically safe, the runner heading to 3B still has the same result as determined in the previous step, & all other runners are safe on a fielder’s choice where no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runner heading to 1B is automatically out, the runner heading to 3B still has the same result as determined in the previous step, & all other runners are either safe on either a fielder’s choice or 3 outs have been recorded & the inning is complete."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is greater than the BsR of the runner heading to 1B, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the infield fielding check is less than or equal to the BsR of the runner heading to 1B, the runner is safe."
      },
      {
        "depth": 1,
        "text": "When there are runners on 1B & 2B with 0 out, the swing is a GB result, an infield fielding check combination of the 1B, 2B, & 3B is available to be used, the fielding score of the 2B is +4 or better, & the fielding score of the 3B is +2 or better, the defensive GM must opt to either take a singular automatic out, a standard GB double play attempt, a 3B-to-1B double play attempt, or 3B-to-2B-to-1B triple play attempt."
      },
      {
        "depth": 2,
        "text": "If the defensive GM opts to take the singular automatic out, a standard GB double play attempt, or a 3B-to-1B double play attempt, the defensive GM then follows the guidelines in the steps above."
      },
      {
        "depth": 2,
        "text": "If the defensive GM opts to attempt a 3B-to-2B-to-1B triple play, the defensive GM then completes the following steps in order."
      },
      {
        "depth": 3,
        "text": "The defensive GM completes the first of 3 infield fielding checks by completing a die roll, against the BsR of the runner heading to 3B."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, all runners are safe on a fielder’s choice where no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runners heading to 3B, 2B, & 1B are out on an automatic 3B-to-2B-to-1B triple play."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & is greater than the BsR of the runner heading to 3B, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & is less than or equal to the BsR of the runner heading to 3B, the runner is safe."
      },
      {
        "depth": 4,
        "text": "If this fielding check fails & the runner heading to 3B is safe, all subsequent runners are also automatically safe."
      },
      {
        "depth": 3,
        "text": "If the first infield fielding check is successful, the defensive GM then completes the second infield fielding check by completing a die roll, now against the BsR of the runner heading to 2B."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, the runners heading to 2B & 1B are automatically safe, the runner heading to 3B still has the same result as determined in the previous step, & all other runners are safe on a fielder’s choice."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runners heading to 2B & 1B are automatically out, 3 outs have been recorded & the inning is complete."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & is greater than the BsR of the runner heading to 2B, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & is less than or equal to the BsR of the runner heading to 2B, the runner is safe."
      },
      {
        "depth": 4,
        "text": "If this fielding check fails & the runner heading to 2B is safe, the subsequent runner heading to 1B is also automatically safe."
      },
      {
        "depth": 3,
        "text": "If the second infield fielding check is successful, the defensive GM then completes the third infield fielding check by completing a die roll, now against the BsR of the runner heading to 1B."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, the runner heading to 1B is automatically safe, the runners heading to 3B & 2B still have the same results as determined in the previous steps, & all other runners are safe on a fielder’s choice."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runner heading to 1B is automatically out, 3 outs have been recorded & the inning is complete."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & is greater than the BsR of the runner heading to 1B, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & is less than or equal to the BsR of the runner heading to 1B, the runner is safe."
      },
      {
        "depth": 1,
        "text": "All standard GB double play, 3B-to-1B double play, & 3B-to-2B-to-1B triple play attempts cannot be attempted on a runner heading toward home plate unless the defensive GM has also declared “infield-in” prior to any die rolls for an at bat."
      },
      {
        "depth": 1,
        "text": "When there are runners on base with less than 2 out, the defensive GM may opt to declare “infield-in” prior to any die rolls in an at bat, which results in the following."
      },
      {
        "depth": 2,
        "text": "PU & FB swing results automatically change to 1B swing results where all runners cannot attempt any extra bases or tag ups."
      },
      {
        "depth": 2,
        "text": "When the bases are loaded & the swing is a GB result, the lead runner heading home is automatically out, & all other runners are automatically safe, advancing 1 base."
      },
      {
        "depth": 2,
        "text": "When there is a runner on 2B, a runner on 3B, runners on both 2B & 3B, or runners on both 1B & 3B, & the swing is a GB result, all existing runners “hold” at their base unless forced to advance 1 base, & the runner heading to 1B is out on a GB result."
      },
      {
        "depth": 3,
        "text": "The offensive GM may opt to counter the existing runners “hold” by declaring “contact-play” to have all existing runners attempt to advance 1 base after a GB result is given, & this choice results in the following."
      },
      {
        "depth": 4,
        "text": "The defensive GM completes a full infield + catcher fielding check, combining the fielding scores of the C, 1B, 2B, 3B & SS + a die roll, against the BsR of the lead runner who attempts to advance 1 base."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, all runners are safe on a fielder’s choice where no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the lead runner is automatically out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the full infield + catcher fielding check is greater than the BsR of the lead runner, the lead runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the full infield + catcher fielding check is less than or equal to the BsR of the lead runner, the lead runner is safe."
      },
      {
        "depth": 4,
        "text": "All existing non-lead runners advance 1 base & the runner heading to 1B is automatically safe."
      },
      {
        "depth": 3,
        "text": "If the offensive GM declines the “contact-play” option, the play is over."
      },
      {
        "depth": 2,
        "text": "When there is a runner on 1B or runners on both 1B & 2B only & the swing is a GB result, the lead runner is automatically out with all other runners advancing 1 base & the runner heading to 1B is safe at 1B on a fielder’s choice result."
      },
      {
        "depth": 1,
        "text": "When there is a runner on 2B with less than 2 outs, the swing is a GB result, & “infield-in” has not been declared with 1B unoccupied, the defensive GM must complete a “Roll-To-See” or RTS to determine if the runner “holds” or advances 1 base to 3B."
      },
      {
        "depth": 2,
        "text": "If the RTS is between 1-10: The runner on 2B advances to 3B & the runner heading to 1B is automatically out on a GB result."
      },
      {
        "depth": 2,
        "text": "If the RTS is between 11-20: The runner on 2B holds, does not advance to 3B, & the runner heading to 1B is automatically out on a GB result."
      },
      {
        "depth": 1,
        "text": "When there is a runner on 3B with less than 2 outs, the swing is a GB result, & “infield-in” has not been declared with 1B unoccupied, the runner on 3B automatically advances 1 base & scores."
      },
      {
        "depth": 1,
        "text": "The defensive GM can issue an intentional walk to the current hitter so long as no die rolls have been made for the current at bat."
      },
      {
        "depth": 2,
        "text": "Once an intentional walk has been announced by the defensive GM, the current hitter is automatically awarded 1B with all other forced runners advancing 1 base."
      },
      {
        "depth": 1,
        "text": "The defensive GM can issue a defensive substitution replacing any fielder with a new fielder off the bench, or replace the current pitcher with a new pitcher out of the bullpen, at any time so long as no die rolls have been made for the current at bat."
      },
      {
        "depth": 2,
        "text": "Fielders are only allowed to shift & change defensive positions during a game when there is another defensive substitution or replacement player entering the game."
      },
      {
        "depth": 0,
        "text": "Managerial Running Decisions"
      },
      {
        "depth": 1,
        "text": "All players who start an at bat on 1B, 2B, &/or 3B are considered existing runners."
      },
      {
        "depth": 1,
        "text": "When a hitter reaches base via a BB, 1B, 1B+, 2B, 3B, or HR swing result, all existing runners automatically advance a specific amount of bases as outlined below."
      },
      {
        "depth": 2,
        "text": "BB, 1B, & 1B+ swing results = All existing runners automatically advance 1 base."
      },
      {
        "depth": 2,
        "text": "2B swing results = All existing runners automatically advance 2 bases."
      },
      {
        "depth": 2,
        "text": "3B & HR swing results = All existing runners automatically score."
      },
      {
        "depth": 1,
        "text": "When there are existing runners on 1B &/or 2B & the swing result is a 1B or 2B, the offensive GM may opt to attempt to take extra bases with existing runners unless a previous result during the at bat specifically states that extra bases cannot be attempted."
      },
      {
        "depth": 2,
        "text": "If the offensive GM declines to attempt to take extra bases, the play is over."
      },
      {
        "depth": 2,
        "text": "If the offensive GM does opt to attempt to take extra bases, the following steps must occur in order."
      },
      {
        "depth": 3,
        "text": "The defensive GM selects the existing runner they will attempt to throw out."
      },
      {
        "depth": 4,
        "text": "If multiple runners attempt to take extra bases, the defensive GM selects only 1 runner to attempt to throw out, with all other extra base attempts being automatically successful unless the runner being thrown at becomes the third out of the inning."
      },
      {
        "depth": 3,
        "text": "The offensive GM completes a “Roll-To-See” or RTS to determine if the attempt to take extra bases is even possible."
      },
      {
        "depth": 4,
        "text": "If the RTS is between 1-10: The attempt to take extra bases is not possible, no runners take any extra bases, & the play is over."
      },
      {
        "depth": 4,
        "text": "If the RTS is between 11-20: The attempt to take extra bases is possible & GMs proceed to the next step below."
      },
      {
        "depth": 4,
        "text": "If there are 2 outs & the defensive GM chooses to try & throw out a runner trying to score, the RTS step is skipped entirely & GMs immediately proceed to the next step below."
      },
      {
        "depth": 3,
        "text": "If the extra base attempt is possible, the defensive GM then completes an outfield fielding check by combining 1 of the 3 fielding scores of the LF, CF, or RF + a die roll against the BsR of the runner they are throwing at."
      },
      {
        "depth": 4,
        "text": "For all extra base attempts, with the exception of 1B to 3B attempts, the runner being thrown at receives an additional +3 BsR speed boost."
      },
      {
        "depth": 4,
        "text": "For all extra base attempts when there are 2 outs, the runner being thrown at also receives another additional +3 BsR speed boost."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, all runners are safe, & no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runner being thrown at is automatically out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the outfield fielding check is greater than the BsR of the runner being thrown at, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the outfield fielding check is less than or equal to the BsR of the runner being thrown at, the runner is safe."
      },
      {
        "depth": 1,
        "text": "When there are existing runners on 1B, 2B &/or 3B & the swing result is a FB, the offensive GM may opt to attempt to tag up with existing runners unless a unless a previous result during the at bat specifically states that extra bases cannot be attempted or the only runner that would be attempting to tag up is an existing runner on 1B heading towards 2B."
      },
      {
        "depth": 2,
        "text": "If the offensive GM declines to attempt to tag up, the play is over."
      },
      {
        "depth": 2,
        "text": "If the offensive GM does opt to attempt to tag up, the following steps must occur in order."
      },
      {
        "depth": 3,
        "text": "The defensive GM selects the existing runner they will attempt to throw out."
      },
      {
        "depth": 4,
        "text": "If multiple runners attempt to tag up, the defensive GM selects only 1 runner to attempt to throw out, with any other tag up attempts being automatically successful unless the runner being thrown at becomes the third out of the inning."
      },
      {
        "depth": 3,
        "text": "The offensive GM completes a “Roll-To-See” or RTS to determine if the attempt to tag up is even possible."
      },
      {
        "depth": 4,
        "text": "If the lead runner attempting to tag up is heading home, even if that runner is not the runner being thrown at, use the following RTS."
      },
      {
        "depth": 4,
        "text": "If the RTS is between 1-10: The attempt to tag up is not possible, no runners tag up, & the play is over."
      },
      {
        "depth": 4,
        "text": "If the RTS is between 11-20: The attempt to tag up is possible & GMs proceed to the next step below."
      },
      {
        "depth": 4,
        "text": "If the lead runner attempting to tag up is heading to 3B, even if that runner is not the runner being thrown at, use the following RTS."
      },
      {
        "depth": 4,
        "text": "If the RTS is between 1-15: The attempt to tag up is not possible, no runners tag up, & the play is over."
      },
      {
        "depth": 4,
        "text": "If the RTS is between 16-20: The attempt to tag up is possible & GMs proceed to the next step below."
      },
      {
        "depth": 3,
        "text": "If the tag up attempt is possible, the defensive GM then completes an outfield fielding check by combining 1 of the 3 fielding scores of the LF, CF, or RF + a die roll against the BsR of the runner they are throwing at."
      },
      {
        "depth": 4,
        "text": "If the runner being thrown at is attempting to tag up from 1B to 2B, then add +10 to all outfield fielding check die rolls."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, all runners are safe, & no outs are recorded."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the runner being thrown at is automatically out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the outfield fielding check is greater than the BsR of the runner being thrown at, the runner is out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the outfield fielding check is less than or equal to the BsR of the runner being thrown at, the runner is safe."
      },
      {
        "depth": 1,
        "text": "If the defensive GM successfully throws out a trailing runner on an extra base or tag up attempt, the lead runner’s extra base attempt is considered to be successful & is completed prior to the throwing out of the trailing runner."
      },
      {
        "depth": 2,
        "text": "For example: If the trailing runner is successfully thrown out for the final out of an inning & the lead runner’s extra base attempt is towards home, the lead runner’s extra base attempt is successful & the run scores prior to the trailing runner being thrown out for the final out of the inning."
      },
      {
        "depth": 1,
        "text": "The defensive GM must also track which outfielders were used during each extra base & tag up attempt combined, with no duplicate outfielder being used 2 times until all outfielders have been used 1 time."
      },
      {
        "depth": 2,
        "text": "For example: If the defensive GM selects the LF for the first extra base or tag up attempt of the game, the LF cannot be used again until all outfield positions have been used 1 time."
      },
      {
        "depth": 3,
        "text": "Once all 3 outfielders have been used for an extra base or tag up attempt 1 time, the counter resets & the process of using all outfielders 2 times begins, continually repeating until the game is complete."
      },
      {
        "depth": 1,
        "text": "When there are runners on base & no die rolls have been completed against the current hitter, the offensive GM may elect to attempt a natural stolen base."
      },
      {
        "depth": 2,
        "text": "Each team reserves the right to attempt up to 1 natural stolen base per game."
      },
      {
        "depth": 3,
        "text": "If there are multiple runners on base, the offensive GM can attempt multiple stolen bases at the exact same time & this counts as only 1 natural stolen base attempt."
      },
      {
        "depth": 4,
        "text": "If the offensive GM elects to attempt multiple stolen bases at the exact same time, the defensive GM selects only 1 runner to attempt to throw out, with all other runners having automatically successful stolen base attempts unless the runner being thrown at makes the third out of the inning."
      },
      {
        "depth": 3,
        "text": "Whenever an at bat takes place and the defensive team has a catcher with a negative fielding score, any stolen bases attempted do not count towards this 1 natural stolen base attempt with unlimited stolen base attempts allowed until a catcher with a positive fielding score or 0 enters the game."
      },
      {
        "depth": 2,
        "text": "Once the offensive GM has declared they are attempting a natural stolen base, the defensive GM then completes a catcher fielding check against the SB score of the runner they are attempting to throw out."
      },
      {
        "depth": 3,
        "text": "If the die roll is a 1, the stolen base attempt is automatically successful, & all runners are safe with the stolen base attempt successful."
      },
      {
        "depth": 3,
        "text": "If the die roll is a 20, the stolen base attempt is automatically unsuccessful, & the stolen base attempt is unsuccessful."
      },
      {
        "depth": 3,
        "text": "If the die roll is not a 1 or 20 & the catcher fielding check is greater than the SB score of the runner, the stolen base attempt is unsuccessful."
      },
      {
        "depth": 3,
        "text": "If the die roll is not a 1 or 20 & the catcher fielding check is less than or equal to the SB score of the runner, the stolen base attempt is successful."
      },
      {
        "depth": 2,
        "text": "If the offensive GM attempts to steal home, add +15 to the catcher fielding check."
      },
      {
        "depth": 2,
        "text": "If the offensive GM successfully completes a stolen base of 2B & there is also a runner on 3B, the offensive GM can elect to complete a second stolen base of home."
      },
      {
        "depth": 3,
        "text": "If the offensive GM elects to complete a second stolen base of home, the defensive GM then completes a full infield + catcher fielding check, combining the fielding scores of the C, 1B, 2B, 3B & SS + a die roll, against the SB score of the runner attempting a second stolen base of home."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 1, the second stolen base attempt of home is automatically successful & all runners are safe."
      },
      {
        "depth": 4,
        "text": "If the die roll is a 20, the second stolen base attempt of home is automatically unsuccessful & the runner is thrown out."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the full infield + catcher fielding check is greater than the SB score of the runner, the second stolen base attempt of home is unsuccessful."
      },
      {
        "depth": 4,
        "text": "If the die roll is not a 1 or 20 & the full infield + catcher fielding check is less than or equal to the SB score of the runner, the second stolen base attempt of home is successful."
      },
      {
        "depth": 1,
        "text": "When the swing result is a 1B+ & 2B is unoccupied after any extra base attempts, the hitter then immediately & automatically attempts a non-natural stolen base of 2B."
      },
      {
        "depth": 2,
        "text": "The defensive GM then completes a catcher fielding check against the runners SB score."
      },
      {
        "depth": 3,
        "text": "If the die roll is a 1, the stolen base attempt is automatically successful."
      },
      {
        "depth": 3,
        "text": "If the die roll is a 20, the stolen base attempt is automatically unsuccessful & the runner is thrown out."
      },
      {
        "depth": 3,
        "text": "If the die roll is not a 1 or 20 & the catcher fielding check is greater than the SB score of the runner, the stolen base attempt is unsuccessful."
      },
      {
        "depth": 3,
        "text": "If the die roll is not a 1 or 20 & the catcher fielding check is less than or equal to the SB score of the runner, the stolen base attempt is successful."
      },
      {
        "depth": 1,
        "text": "When the swing result is a 1B+ & 2B is occupied after any extra base attempts, no automatic non-natural stolen base attempt occurs & the play is over."
      },
      {
        "depth": 1,
        "text": "Any die rolls completed prior to the defensive GM selecting the runner they are attempting to throw out where multiple runners are attempting to take extra bases, tag up, or steal a base, are void & to be re-rolled after the runner is formally selected."
      },
      {
        "depth": 1,
        "text": "When no die rolls have been completed against the current hitter, the offensive GM may substitute out an existing runner for a pinch runner &/or the current hitter for a pinch hitter off their bench so long as the replacement player has not yet appeared in the current game."
      },
      {
        "depth": 0,
        "text": "Bunting"
      },
      {
        "depth": 1,
        "text": "The offensive GM reserves the right to attempt a sacrifice bunt when there are runners on both 1B & 2B with 3B unoccupied, runners on both 1B & 3B with 2B unoccupied, a runner on 2B with 3B unoccupied, or a runner on 1B with 2B unoccupied, & no die rolls have been completed against the current hitter."
      },
      {
        "depth": 2,
        "text": "Once the offensive GM announces the sacrifice bunt attempt, the defensive GM may opt to counter the attempt by declaring “wheel play” which results in the following “Roll-To-See” or RTS to determine the result."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 1-15: The bunt attempt is successful, all forced runners advance 1 base, & the hitter is safe at 1B on a fielder’s choice where no outs are recorded"
      },
      {
        "depth": 3,
        "text": "If the RTS is between 16-20: The lead runner attempting to advance 1 base is out on a fielder’s choice where all other forced runners advance 1 base, & the hitter is safe at 1B on a fielder’s choice"
      },
      {
        "depth": 2,
        "text": "If the defensive GM does not declare the “wheel play” is on, the defensive GM then still completes a RTS to determine the result, broken down by the following."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 1-2: The sacrifice bunt attempt is not possible."
      },
      {
        "depth": 4,
        "text": "If the sacrifice bunt result is not possible, the next roll is for swing for the at bat, & this roll is now automatically on the pitcher’s chart."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 3-4: The sacrifice bunt is unsuccessful & the hitter is out on a K result."
      },
      {
        "depth": 3,
        "text": "If the RTS is a 5: The sacrifice bunt is unsuccessful, the lead runner is automatically out, & the hitter is safe at 1B on a fielder’s choice."
      },
      {
        "depth": 3,
        "text": "If the RTS is between 6-20: The sacrifice bunt is successful, the lead runner advances 1 base, any other forced runners advance 1 base, & the hitter is out at 1B."
      },
      {
        "depth": 4,
        "text": "If the sacrifice bunt is successful & runners were on 1B & 3B, the runner on 3B holds & remains at 3B under all scenarios."
      },
      {
        "depth": 1,
        "text": "The offensive GM reserves the right to attempt a squeeze bunt any time there is an existing runner on 3B, the bases are not loaded, & “infield-in” has not been declared."
      },
      {
        "depth": 2,
        "text": "Once the offensive GM has announced their intention to squeeze bunt, the offensive GM then immediately completes a standard die roll for the swing."
      },
      {
        "depth": 3,
        "text": "If the standard die roll is 1-7, the runner on 3B is automatically out on an unsuccessful stolen base attempt of home & no squeeze bunt attempt occurs."
      },
      {
        "depth": 3,
        "text": "If the standard die roll is 8-15, the runner on 3B is out at home on a fielder’s choice with the hitter safe at 1B & any other runners advancing 1 base."
      },
      {
        "depth": 3,
        "text": "If the standard die roll is 16-19, the runner on 3B is safe at home, & the hitter is automatically out at 1B on a GB result."
      },
      {
        "depth": 3,
        "text": "If the standard die roll is 20, the runner on 3B is safe at home, & the hitter is also safe at 1B on a fielder’s choice, with no outs recorded."
      },
      {
        "depth": 1,
        "text": "Once any bunt has been declared by the offensive GM, the decision is final & is irrevocable."
      },
      {
        "depth": 0,
        "text": "Chartless Players"
      },
      {
        "depth": 1,
        "text": "Players that do not have an On Base score, BsR score, &/or SB score on their card have the following default player attributes at all times:"
      },
      {
        "depth": 2,
        "text": "On Base score = 5"
      },
      {
        "depth": 2,
        "text": "BsR & SB score = 10"
      },
      {
        "depth": 3,
        "text": "The player’s handedness for pitching also defaults as their handedness for hitting in chartless scenarios."
      },
      {
        "depth": 1,
        "text": "Players that take an at bat while using default player attributes & earn the offensive advantage, use the following default hitter chart:"
      },
      {
        "depth": 2,
        "text": "PU range = 1-3"
      },
      {
        "depth": 2,
        "text": "K range = 4-10"
      },
      {
        "depth": 2,
        "text": "GB range = 11-17"
      },
      {
        "depth": 2,
        "text": "FB range = 18-20"
      },
      {
        "depth": 3,
        "text": "All other hitter chart result ranges are not possible."
      },
      {
        "depth": 1,
        "text": "Players that do not have a Control score &/or IP score on their card have the following default player attributes at all times:"
      },
      {
        "depth": 2,
        "text": "Control score = -5"
      },
      {
        "depth": 2,
        "text": "IP score = 0.0"
      },
      {
        "depth": 3,
        "text": "The player’s handedness for hitting also defaults as their handedness for pitching in chartless scenarios."
      },
      {
        "depth": 1,
        "text": "Players that pitch while using default player attributes & earn the pitching advantage, use the following default pitcher chart:"
      },
      {
        "depth": 2,
        "text": "PU range = 1"
      },
      {
        "depth": 2,
        "text": "K range = 2"
      },
      {
        "depth": 2,
        "text": "GB range = 3-7"
      },
      {
        "depth": 2,
        "text": "FB range = 8-11"
      },
      {
        "depth": 2,
        "text": "BB range = 12-14"
      },
      {
        "depth": 2,
        "text": "1B range = 15-17"
      },
      {
        "depth": 2,
        "text": "2B range = 18"
      },
      {
        "depth": 2,
        "text": "3B range = 19"
      },
      {
        "depth": 2,
        "text": "HR range = 20"
      },
      {
        "depth": 1,
        "text": "GMs always reserve the right to have any player who is appearing in a game use default player attributes instead of their card attributes in order to avoid accruing fatigue effects."
      }
    ]
  },
  {
    "id": "section-8",
    "number": 8,
    "title": "Player Fatigue & Effects",
    "lines": [
      {
        "depth": 1,
        "text": "Fatigue Score Overview"
      },
      {
        "depth": 2,
        "text": "Each player has a fatigue score on their card which states how many games of rest that a player needs between plate appearances for offensive fatigue scores & between pitching appearances for pitching fatigue scores in order to become fully rested, reset their fatigue score, & play in their next game without any lingering fatigue effects."
      },
      {
        "depth": 3,
        "text": "Players who appear as defensive replacements or pinch runners only & do not record a plate appearance in a game do not have this type of appearance count against their fatigue scores & can appear in this manner an unlimited amount of times without receiving fatigue effects."
      },
      {
        "depth": 2,
        "text": "Players who qualify as both a hitter & pitcher have 2 separate fatigue scores on their card, with each score corresponding independently to appearances as either a hitter or pitcher."
      },
      {
        "depth": 3,
        "text": "Since these players have 2 independent fatigue scores, these types of players may have scenarios where they have fatigue effects as a hitter but not as a pitcher, or fatigue effects as a pitcher but not as a hitter, as they may have appearances as solely a hitter or pitcher only, which would make their fatigue scores different over multiple games."
      },
      {
        "depth": 2,
        "text": "GMs may opt to substitute a player out of a game in order to avoid having a player continue in a game & accrue fatigue effects so long as the substitution takes place prior to any die rolls for the current plate at bat."
      },
      {
        "depth": 2,
        "text": "GMs may opt to bench players prior to the start of a game in order to avoid having a player play in a game with fatigue effects &/or play in a game & accrue fatigue effects."
      },
      {
        "depth": 0,
        "text": "Pre-Game Fatigue Effects"
      },
      {
        "depth": 1,
        "text": "Hitters who have played in a previous game & have not yet fully reset their fatigue score are subject to the following fatigue effects:"
      },
      {
        "depth": 2,
        "text": "For each game that a hitter is away from resetting their fatigue score, subtract that total number of games from their On Base score during each at bat."
      },
      {
        "depth": 3,
        "text": "For example: If a hitter with an On Base 12 score enters into a game while they are 2 games away from resetting their fatigue score, they will have a On Base 10 score during the entirety of the current game (-1 for each game away from resetting their fatigue score)."
      },
      {
        "depth": 2,
        "text": "Each game that a hitter makes a plate appearance prior to fully resetting their fatigue score, their full card fatigue score is then added to the number of games remaining to fully reset their fatigue score at the conclusion of each game."
      },
      {
        "depth": 3,
        "text": "For example: If a hitter with an On Base 12 score & on-card fatigue score of 6 receives a plate appearance in a game while they are 2 games away from resetting their fatigue score, they will then be 8 games away from resetting their fatigue score heading into the following game (-1 for each game away from resetting their fatigue score after receiving a plate appearance in the current game + -6 which is their on-card fatigue score)."
      },
      {
        "depth": 2,
        "text": "Hitters can never have an On Base score lower than On Base 5 at any time."
      },
      {
        "depth": 1,
        "text": "Starting pitchers who have played in a previous game, & not yet fully reset their fatigue score are subject to the following fatigue effects:"
      },
      {
        "depth": 2,
        "text": "For each game that a starting pitcher is away from resetting their fatigue score, subtract that total number of games from their Control score during each at bat."
      },
      {
        "depth": 3,
        "text": "For example: If a starting pitcher with a Control 6 score starts the current game while they are 2 games away from resetting their fatigue score, they will start the game with a Control 4 score & this score will remain during the entirety of the current game, unless any in-game fatigue effects are also applied (-1 for each game away from resetting their fatigue score)."
      },
      {
        "depth": 2,
        "text": "Each game that a starting pitcher makes an appearance prior to fully resetting their fatigue score, their full card fatigue score is then added to the number of games remaining to fully reset their fatigue score, at the conclusion of each game."
      },
      {
        "depth": 3,
        "text": "For example: If a starting pitcher with a Control 6 score & on-card fatigue score of 5 enters into a game while they are 2 games away from resetting their fatigue score, they will be 7 games away from resetting their fatigue score heading into the following game (-1 for each game away from resetting their fatigue score when entering the current game + -5 which is their on-card fatigue score)."
      },
      {
        "depth": 2,
        "text": "Starting pitchers who had their most recent appearance in a previous game as a relief appearance & have not yet fully reset their fatigue score at the start of the current game have their full card fatigue score added to the number of games remaining to fully reset their fatigue score at the conclusion of each game."
      },
      {
        "depth": 3,
        "text": "For example: A pitcher with Control 6 & on-card fatigue score of 2, who had their most recent appearance in a previous game as a relief pitcher & has not yet fully reset their fatigue score since that relief appearance, starts the current game while they are 2 games away from resetting their fatigue score, they will then be 4 games away from resetting their fatigue score heading into the following game (-1 for each game away from resetting their fatigue score when entering the current game + -2 which is their on-card fatigue score)."
      },
      {
        "depth": 1,
        "text": "Relief pitchers who have pitched in a previous game & not yet fully reset their fatigue score are subject to the following fatigue effects:"
      },
      {
        "depth": 2,
        "text": "For each game that a relief pitcher is away from resetting their fatigue score, subtract that total number of games from their Control score during each at bat."
      },
      {
        "depth": 3,
        "text": "For example: If a relief pitcher with a Control 6 score enters into a game while they are 2 games away from resetting their fatigue score, they will have a Control 4 score during the entirety of the current game unless any in-game fatigue effects are also applied (-1 for each game away from resetting their fatigue score)."
      },
      {
        "depth": 2,
        "text": "Each game that a relief pitcher makes an appearance prior to fully resetting their fatigue score, their full card fatigue score is then added to the number of games remaining to fully reset their fatigue score, at the conclusion of each game."
      },
      {
        "depth": 3,
        "text": "For example: If a relief pitcher with a Control 6 score & on-card fatigue score of 2 enters into a game while they are 2 games away from resetting their fatigue score, they will be 4 games away from resetting their fatigue score heading into the following game (-1 for each game away from resetting their fatigue score when entering the current game + -2 which is their on-card fatigue score)."
      },
      {
        "depth": 2,
        "text": "All pitchers can never have a Control score lower than Control -5 at any time."
      },
      {
        "depth": 1,
        "text": "Pitchers who retire the minimum number of batters faced in an appearance & are not appearing in back-to-back games having no rest days in between appearances are awarded an efficiency bonus +1 to their post game fatigue score."
      },
      {
        "depth": 2,
        "text": "For example: A pitcher with a fatigue score of 1 who did not pitch in the previous game enters a game and retires 3 straight batters.  After the game the pitcher normally would need 1 day of rest in order to appear in his next game at no fatigue, but since he retired the minimum amount of batters, he can appear in the next game with no fatigue effects in place."
      },
      {
        "depth": 0,
        "text": "In-Game Distance Fatigue Effects"
      },
      {
        "depth": 1,
        "text": "For each appearance that relief pitchers make pitching beyond their card IP length that also goes beyond 1.0 IP in total length, 1 additional game is added to the total number of games needed to reset their fatigue score at the end of the game."
      },
      {
        "depth": 2,
        "text": "For example: A relief pitcher with Control 6 enters a game 2 games away from resetting their fatigue score & has a card IP length of 1.0 with a fatigue score of 6. The pitcher then pitches 2.0 IP in the current game. After the conclusion of the current game, the pitcher will then need 9 games to reset their fatigue score (-2 games from fully resetting at the start of the game + -1 game for pitching beyond their card IP length + -6 games from their card fatigue score)."
      },
      {
        "depth": 1,
        "text": "For each out that all pitchers record pitching beyond their card IP length, -2 is subtracted from their current Control score in the current game until the pitcher is removed."
      },
      {
        "depth": 2,
        "text": "For example: A pitcher with a Control 6 score has pitched 0.2 IP past their card IP length with no other active fatigue effects. This pitcher will have a Control 2 score for the next hitter (-2 for each out recorded beyond their card IP length totaling -4)."
      },
      {
        "depth": 1,
        "text": "For pitchers who have recorded at least 15 outs, allowed 0 earned runs & 0 inherited runners to score in the current game, they receive a “Shutout Bonus” & only -1 is subtracted from their Control score for each out in the current game that the pitcher records pitching beyond their card IP length. up until the pitcher has a Control score of 0 where the Control score remains until the pitcher is removed or allows an earned run."
      },
      {
        "depth": 2,
        "text": "For example: A pitcher with a Control 6 score has pitched 1.1 IP past their card IP length having already pitched 5.0 IP & allowed 0 earned runs. This pitcher will have a Control 2 score for the next hitter (-1 for each 0.1 out recorded beyond their card IP length)."
      },
      {
        "depth": 3,
        "text": "Pitchers who have card IP scores of less than 5.0 IP have standard IP fatigue effects applied to them until they reach 15 outs & then these modified fatigue effects are applied going forward."
      },
      {
        "depth": 2,
        "text": "If the current pitcher is over their card IP length & then allows an earned run, immediately subtract -2 from the current Control of the pitcher & then subtract -2 for each subsequent out recorded until the pitcher is removed from the game."
      },
      {
        "depth": 3,
        "text": "For example: A pitcher with a Control 6 score has pitched 1.1 IP past their card IP length having already pitched 5.0 IP & allowed 0 earned runs. This pitcher will have a Control 2 score for the next hitter (-1 for each 0.1 out recorded beyond their card IP length).  The next hitter then hits a HR.  The pitcher will then have a Control 0 score for the following hitter.  If that hitter records an out, the pitcher will have a Control -2 score for the next hitter."
      },
      {
        "depth": 2,
        "text": "If the current pitcher has a negative Control score when the Shutout Bonus comes into effect, the pitcher does not see any reduction in Control score until the pitcher is removed or allows an earned run."
      },
      {
        "depth": 1,
        "text": "Pitchers who start a game with Control 1 or higher & exit a game after having thrown a pitch to a hitter while having Control -1 or lower receive an additional 1 game added to their fatigue score, regardless of if they are a starting pitcher or relief pitcher."
      },
      {
        "depth": 1,
        "text": "All of the above in-game distance fatigue effects are in addition to any pre-game fatigue effects from Section IX Player Fatigue & Effects subpart B: Pre-Game Fatigue Effects."
      },
      {
        "depth": 0,
        "text": "In-Game Performance Fatigue Effects"
      },
      {
        "depth": 1,
        "text": "Pitchers are immediately subject to the following fatigue effects after allowing a specific amount of earned runs, which are broken down by the following:"
      },
      {
        "depth": 2,
        "text": "Pitchers that have allowed 4 or more earned runs = -1 from their Control score for the remainder of the current game."
      },
      {
        "depth": 2,
        "text": "Pitchers that have allowed 7 or more earned runs = -3 from their Control score for the remainder of the current game."
      },
      {
        "depth": 2,
        "text": "Pitchers that have allowed 8 or more earned runs = -6 from their Control score for the remainder of the current game."
      },
      {
        "depth": 2,
        "text": "Pitchers that have allowed 9 or more earned runs = -10 from their Control score for the remainder of the current game."
      },
      {
        "depth": 2,
        "text": "Pitchers that have allowed 10 or more earned runs = -15 from their Control score for the remainder of the current game."
      },
      {
        "depth": 3,
        "text": "Pitchers can never have a Control score lower than Control -5 due to any fatigue effects at any time."
      },
      {
        "depth": 1,
        "text": "All of the above in-game performance fatigue effects are in addition to any other fatigue effects from Section IX Player Fatigue & Effects subpart B: Pre-Game Fatigue Effects and/or Section IX Player Fatigue & Effects subpart C: In-Game Distance Fatigue Effects."
      }
    ]
  }
] as const
